WSL-Helper: Force stop process as needed.
rancher-sandbox/rancher-desktop pull request #1068
Opened 2021-12-04 02:21 UTC by mook-as

It seems like killing the `wsl.exe` process (and therefore the controlling terminal) does not always send `SIGTERM` (or even `SIGHUP`) to the Linux-side process.  This PR implements an extra command on `wsl-helper` to manually find the process and terminate it, instead.

Also includes some fixups to debug logging, which was used to figure out what was going wrong…

Fixes #1059.

2021-12-07 18:50 UTC, ericpromislow commented on src/go/wsl-helper/pkg/process/kill_others.go
> +	var argsBytes []byte
Could use a comment that the words in `/proc/*/cmdline` are null-byte separated

2021-12-07 20:05 UTC, ericpromislow requested changes

2021-12-07 20:05 UTC, ericpromislow commented on src/k8s-engine/wsl.ts
> +        console.debug(`Capturing output: wsl.exe ${ args.join(' ') }`);
Ahh, nice, we have `console.debug` now and don't have to worry about managing them as much.

2021-12-07 20:06 UTC, ericpromislow commented
Got an error running this branch. The integrations page checkbox was disabled, with a message that

2021-12-08 01:49 UTC, mook-as commented
> Got an error running this branch. The integrations page checkbox was disabled, with a message `Error: wsl.exe exited with code 11`

Ugh. That's a segfault (signal 11).

With some experimenting, it looks like WSL has a caching problem: if you modify the executable, sometimes it'll get confused.  I could reproduce this in _one_ of my WSL2 distros, but not if I rebuild the `wsl-helper` binary.  It went away after `wsl --shutdown`.  Running it under gdb claims it's around [early startup](https://github.com/golang/go/blob/go1.17.4/src/runtime/runtime1.go#L431), outside of our code.

This shouldn't be a problem in the field, given that users aren't going to be recompiling executables all the time :)

2021-12-13 20:22 UTC, ericpromislow submitted a review, later dismissed
Works fine.

2021-12-14 18:42 UTC, ericpromislow requested changes
1. I realize I need more context on what the `BackgroundProcess`  class is for.

2. Why are there both `resources/linux/wsl-helper` and `resources/linux/bin/wsl-helper`? They're different sizes, and probably need different names.

3. I'm observing `wsl-helper kill` getting called about every 50 seconds when integration is on. Is this expected? If yes, why (so needs a comment somewhere). If not, that would be a bug.

2021-12-14 18:50 UTC, mook-as commented
1. It is used to run a persistent background process on the Window side.  We don't have OpenRC on Windows, essentially.  We have a rd agent, plus the various proxy processes.
2. `resources/linux/bin/wsl-helper` should no longer exist; that was from a previous run.  This changed in #1080.  Please delete it and try again (it will no longer get built).
3. I'll go take a look and answer later; that's not expected at all — `wsl-helper kill` should get run when the proper Linux-side process disconnects, to ensure that things are properly dead (because sometimes when we kill the Windows side WSL-internal proxy process, the Linux side process stays alive).

2021-12-14 21:14 UTC, ericpromislow commented
And in answer top https://github.com/rancher-sandbox/rancher-desktop/pull/1068#issuecomment-993878548, points 2 and 3 are both due to the presence of an older `wsl-helper` process running in the Ubuntu WSL that couldn't be deleted by the new branch because the path had changed.

2021-12-14 21:28 UTC, ericpromislow approved these changes
All issues I identified earlier today (2021-12-14) have been addressed.

2021-12-14 21:29 UTC, merged