Properly source /etc/environment in /etc/init.d/k3s
rancher-sandbox/rancher-desktop pull request #1565
Opened 2022-02-10 08:40 UTC by jandubois

/etc/environment does not use shell syntax, so cannot be sourced directly via `source /etc/environment`.

Addresses https://github.com/rancher-sandbox/rancher-desktop/issues/578#issuecomment-1033607536

2022-02-10 17:56 UTC, mook-as requested changes
For reference, [pam_env](https://manpages.ubuntu.com/manpages/bionic/en/man8/pam_env.8.html), [systemd](https://www.freedesktop.org/software/systemd/man/environment.d.html).

I don't think this will deal with empty lines correctly, `export ""` errors.

2022-02-11 00:29 UTC, jandubois commented
Updated the PR to implement the logic from https://github.com/linux-pam/linux-pam/blob/master/modules/pam_env/pam_env.c

Only difference (that I'm aware of) is that this script doesn't replace one or two quotes by just the empty string.

Manual testing:

```console
lima-rancher-desktop:~# cat /etc/environment
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#

FOO1=foo $bar baz
FOO2="foo $bar baz"
	FOO3=foo $bar baz
  export FOO4=foo $bar baz

FOO5='foo $bar baz"
FOO6="foo $bar baz"
#
FOO7="foo#$bar baz"
FOO8=foo#$bar $baz
FOO9='
FOOA=""

#LIMA-START
#LIMA-END

lima-rancher-desktop:~# source /tmp/rancher-desktop/export-env

lima-rancher-desktop:~# env | grep ^FOO | sort -g
FOO1=foo $bar baz
FOO2=foo $bar baz
FOO3=foo $bar baz
FOO4=foo $bar baz
FOO5=foo $bar baz
FOO6=foo $bar baz
FOO7=foo
FOO8=foo
FOO9='
FOOA=""
```

2022-02-11 22:15 UTC, mook-as requested changes

2022-02-11 22:47 UTC, jandubois commented on src/assets/scripts/service-k3s.initd
> +        line=$(echo "$line" | sed -E "s/^[ \\t]*(export )?//; s/#.*//; s/(^[^=]+=)[\"'](.*[^\"'])?[\"']?$/\1\2/")
Doesn't seem to be necessary:

```console
$ FOO=foo bar baz
-bash: bar: command not found

$ FOO=$(echo foo bar baz)
$ echo $FOO
foo bar baz

$ FOO="$(echo foo bar baz)"
$ echo $FOO
foo bar baz
```

You want me to change it?

2022-02-11 22:49 UTC, jandubois commented on src/assets/scripts/service-k3s.initd
> +        line=$(echo "$line" | sed -E "s/^[ \\t]*(export )?//; s/#.*//; s/(^[^=]+=)[\"'](.*[^\"'])?[\"']?$/\1\2/")
> You want me to change it?

Nm, I changed it. Looks better quoted, so you don't have to think about it.

2022-02-12 01:15 UTC, mook-as approved these changes

2022-02-12 01:16 UTC, merged