WSL: fix WSL paths in different distributions.
rancher-sandbox/rancher-desktop pull request #1586
Opened 2022-02-14 23:00 UTC by mook-as

The mapping of Windows paths to Linux paths in WSL can be different per distribution (due to the ability to have different [root paths](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings)); this change ensures we look it up per distribution.

Fixes #1377.

2022-02-15 20:56 UTC, ericpromislow commented
I added the `root = /` line to wsl.conf, and get the mount errors on loading both before and after applying this PR. On a second run the UI didn't come up, and didn't come up after I deleted the `root = /` line. Will clear and retry.

2022-02-15 21:50 UTC, ericpromislow requested changes
Not working with the `root = /` line in `/etc/wsl.conf`

2022-02-15 21:59 UTC, ericpromislow requested changes
Can't get it to work.

2022-02-16 00:40 UTC, mook-as commented on src/go/nerdctl-stub/main_linux.go
> +			return fields[4], nil
Yeah, the check here was dumb; fixed it to look for `wsl` (because it's <root>/wsl`, as in `/mnt/wsl` vs `/mnt/c`, etc.).

2022-02-22 21:09 UTC, ericpromislow commented
Same error message on startup after pulling in everything up to commit `wsl-helper: Provide fallback for getting /mnt/wsl`:
```
Last command run:
wsl --distribution rancher-desktop --exec mount -o bind /mnt/wsl/rancher-desktop/run/data/var/lib /var/lib

Context:
Mounting WSL data
...
2022-02-22T21:05:18.214Z: Running command wsl --distribution rancher-desktop 
    --exec mount -o bind /mnt/wsl/rancher-desktop/run/data/etc/rancher /etc/rancher...
2022-02-22T21:05:18.219Z: Running command wsl --distribution rancher-desktop 
    --exec mount -o bind /mnt/wsl/rancher-desktop/run/data/var/lib /var/lib...
2022-02-22T21:05:18.330Z: WSL: executing: mount -o bind /mnt/wsl/rancher-desktop/run/data/etc/rancher 
/etc/rancher: Error: wsl.exe exited with code 255
2022-02-22T21:05:18.343Z: WSL: executing: mount -o bind /mnt/wsl/rancher-desktop/run/data/var/lib /var/lib: 
Error: wsl.exe exited with code 255
```

2022-02-22 21:10 UTC, ericpromislow requested changes
Same error when setting `root = /` in `/etc/wsl.conf`:

```
2022-02-22T21:05:18.330Z: WSL: executing: mount -o bind /mnt/wsl/rancher-desktop/run/data/etc/rancher 
/etc/rancher: Error: wsl.exe exited with code 255
2022-02-22T21:05:18.343Z: WSL: executing: mount -o bind /mnt/wsl/rancher-desktop/run/data/var/lib /var/lib: 
Error: wsl.exe exited with code 255
```

2022-02-22 21:31 UTC, ericpromislow approved these changes
Works fine once Mark told me how it use it.

2022-02-22 21:31 UTC, merged