Explicitly invoke showAboutPanel when clicking About
rancher-sandbox/rancher-desktop pull request #1691
Opened 2022-03-01 21:17 UTC by rak-phillip

This shows the about panel by explicitly invoking `Electron.app.showAboutPanel()` when clicking on About. 

Spent some time researching why the existing implementation might not be working Linux vs. Windows. Unfortunately, I came up empty-handed in my search. Will do some testing in Windows to see if this affects Windows as well..

closes #738 

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>

2022-03-03 16:16 UTC, rak-phillip commented
Confirmed that this change doesn't change the way the about panel behaves in Windows.

2022-03-04 13:32 UTC, thehejik approved these changes
Works on Linux. Thanks!
![rd-about-linux](https://user-images.githubusercontent.com/12828077/156772314-45412754-4651-4cca-90a5-bb515c444db2.png)

2022-03-04 17:19 UTC, adamkpickering requested changes
If we are making the version info available this way, perhaps we can remove the version info from the General tab. Maybe it would be best to check this with Jan/Matt first though.

Otherwise looks good. I also tested this on Linux and it works great.

2022-03-04 18:50 UTC, rak-phillip commented
> If we are making the version info available this way, perhaps we can remove the version info from the General tab. Maybe it would be best to check this with Jan/Matt first though.
> 
> Otherwise looks good. I also tested this on Linux and it works great.

That's a great call out and definitely something we can discuss, but I think it's out of scope for the issue this PR addresses.

2022-03-04 19:20 UTC, adamkpickering approved these changes

2022-03-04 19:20 UTC, adamkpickering commented
Ok fair enough, we can do it later.

2022-03-04 19:21 UTC, merged

2022-03-04 20:13 UTC, jandubois commented
> If we are making the version info available this way, perhaps we can remove the version info from the General tab.

I like having the version number on the General tab. It is redundant with the About box, but I would rather get rid of the About box then (because unlike the General tab, I have to press a button to dismiss it).

I understand that having an about box is customary, even if useless/redundant, so I would rather leave everything as-is and not have any followup action at all. 😄