Wait for wsl-init to finish before moving on with wsl setup.
rancher-sandbox/rancher-desktop pull request #2073
Opened 2022-04-22 07:55 UTC by vladonemo

Partially fixes #1919

2022-04-22 17:05 UTC, mook-as requested changes
Is my understanding correct that this is trying to fix an issue were `/var/lib` / `/etc/rancher` are not staying mounted for `wsl-init`?

If that is the case, I think this fix is not all the way correct: the desired flow is that `this.mountData()` (line 1203) mounts things, and `wsl-init` sees it.  However, I guess it's possible that the machine is busy enough that none of the other WSL processes start before all the WSL processes in `this.mountData()` exits (expected) _and_ WSL times out the idle distro and terminates it (unexpected).  In this case, I believe a proper fix would be:
- Make `this.mountData()` spawn a process that stays running (to prevent the distro from shutting down); presumably this would have to be returned (as a [`ChildProcess`](https://nodejs.org/docs/latest-v16.x/api/child_process.html#class-childprocess))
- Run `wsl-init` and friends, as we do now.
- Terminate the process we got from the first step; at this point `wsl-init` is actively running so the VM still can't auto-terminate.

Thanks for your PR! However, it doesn't appear to actually eliminate the cause (unless I'm misunderstanding what the cause is, in which case please let me know).

2022-04-22 18:18 UTC, vladonemo commented on src/k8s-engine/wsl.ts
> +6
oh, my bad.

2022-04-22 18:19 UTC, vladonemo commented on src/k8s-engine/wsl.ts
>            this.progressTracker.action(this.lastCommandComment, 100, async() => {
right, haven't realized it's just a single one. thanks

2022-04-22 20:12 UTC, vladonemo commented
> Is my understanding correct that this is trying to fix an issue were `/var/lib` / `/etc/rancher` are not staying mounted for `wsl-init`?
> 
> If that is the case, I think this fix is not all the way correct: the desired flow is that `this.mountData()` (line 1203) mounts things, and `wsl-init` sees it. However, I guess it's possible that the machine is busy enough that none of the other WSL processes start before all the WSL processes in `this.mountData()` exits (expected) _and_ WSL times out the idle distro and terminates it (unexpected). In this case, I believe a proper fix would be:
> 
> * Make `this.mountData()` spawn a process that stays running (to prevent the distro from shutting down); presumably this would have to be returned (as a [`ChildProcess`](https://nodejs.org/docs/latest-v16.x/api/child_process.html#class-childprocess))
> * Run `wsl-init` and friends, as we do now.
> * Terminate the process we got from the first step; at this point `wsl-init` is actively running so the VM still can't auto-terminate.
> 
> Thanks for your PR! However, it doesn't appear to actually eliminate the cause (unless I'm misunderstanding what the cause is, in which case please let me know).

Could you please elaborate on the 'WSL times out the idle distro and terminates it'? I don't know this feature of WSL. 

The code awaits until the `mountData` finishes fully. Then it starts the WSL env (the whole block with `runInit` at the end). And only after this is done (awaiting the `wsl-init.pid`) the installation continues. I must admit, I still don't fully understand the actual root cause, but I believe that running (one of the) installations in parallel to the `runInit` leads to the race condition.

2022-04-22 20:13 UTC, vladonemo commented on src/k8s-engine/wsl.ts
> +          await this.progressTracker.action('Installing k3s', 100, async() => {
right, will do so

2022-04-22 20:30 UTC, mook-as commented
Hi!
I'm referring to [this bit in the WSL documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#the-8-second-rule), where it describes how WSL will terminate a distribution after about 8 seconds. We're actually kind of depending on this right now, since `mountData()` fully exists, and we expect `wsl-init` to see the same mounts from there (even though WSL could have terminated the distribution within that window between the two function calls, losing the mount information).

I'm suggesting keeping a (WSL) process around across that gap, so that WSL cannot terminate our distribution before `wsl-init` start running.

2022-04-23 10:02 UTC, vladonemo commented
Ah, ok, now I see. You mean the 8 seconds rule after approximately which the distro is stopped. Thanks for the explanation. I understand it now. Will implement it according to your suggestion.

2022-04-23 10:39 UTC, vladonemo commented
I reverted all my previous changes and implemented as per your suggestion. The `mountData` now spawns a child process (plain `sh`) which is killed after the `runInit` finishes. Tested it and it starts OK now ;)

2022-04-25 18:02 UTC, mook-as requested changes
Thanks for the changes! Just some smaller fixes now.

2022-04-25 18:02 UTC, mook-as commented on src/k8s-engine/wsl.ts
> +            lock.kill('SIGTERM');
This should always run, so there should be a `try/finally` somewhere.

I thinking something like
```ts
try {
  await Promise.all(installerActions);
} finally {
  lock.kill('SIGTERM');
}
```
Note that this code is Windows-only, so [according to docs](https://nodejs.org/docs/latest-v16.x/api/child_process.html#subprocesskillsignal) the arugment here doesn't matter and the process is always killed with a `TerminateProcess`.

2022-04-25 18:02 UTC, mook-as commented on src/k8s-engine/wsl.ts
> +      lock.kill('SIGTERM');
See above — `try/finally` here too please.

2022-04-25 20:20 UTC, mook-as commented
Hi! We're trying to land this for an impending release; I've pushed the changes I want to your branch (on top of your commits) and I'll arrange for a review shortly.

Thanks!

2022-04-25 20:21 UTC, mook-as approved these changes

2022-04-25 20:41 UTC, rak-phillip approved these changes
Changes look good and pass smoke tests 🙂

2022-04-25 21:41 UTC, merged