Always ignore stdin for docker-cred list checks.
rancher-sandbox/rancher-desktop pull request #2331
Opened 2022-06-03 22:34 UTC by ericpromislow

Signed-off-by: Eric Promislow <epromislow@suse.com>

2022-06-03 22:40 UTC, mook-as approved these changes
Context: we're hitting issues on Linux, where we sometimes see `EPIPE` when the input isn't read.

This will hopefully fix #2329

2022-06-03 23:20 UTC, jandubois requested changes
Changing the default credstore on Linux from `pass` to `secretservice` has not been discussed/agreed on.

2022-06-03 23:20 UTC, jandubois commented on src/utils/dockerDirManager.ts
> +      return 'secretservice';
This has nothing to do with ignoring stdin and seems like a change in functionality.

2022-06-06 17:39 UTC, mook-as submitted a review, later dismissed
Seems to fix the `EPIPE` issue.

Tested on OpenSUSE Leap 15.3 (installed `password-store` and `gnutls`).

2022-06-06 19:31 UTC, mook-as approved these changes
The PR doesn't really do what it says on the tin anymore, but :shrug:

2022-06-06 19:47 UTC, mook-as approved these changes

2022-06-06 20:29 UTC, merged