make vtunnel configurable 1/2
rancher-sandbox/rancher-desktop pull request #2436
Opened 2022-06-21 17:21 UTC by Nino-K

This makes vtunnel configurable which allows us to add any number of tunnels with configuration only and no code change required. 

Please note there will be a follow-up PR 2/2 which includes additional changes (integration code into Rancher Desktop).

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-06-21 20:42 UTC, mook-as requested changes
Just some trivial changes.

I think  you mentioned before wanting to go for one handshake across all vtunnels (because they all go to the same VM anyway); that might be a good follow up? I'm totally fine with merging this without that.

2022-06-21 20:42 UTC, mook-as commented on src/go/vtunnel/test/e2e/connectivity_test.go
> +	"gopkg.in/yaml.v3"
```suggestion
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"

	"github.com/rancher-sandbox/rancher-desktop/src/go/vtunnel/pkg/config"
```

2022-06-23 21:00 UTC, mook-as approved these changes

2022-06-24 18:09 UTC, merged

2022-07-07 16:34 UTC, Nino-K commented
Related to: https://github.com/rancher-sandbox/rancher-desktop/issues/2327