Implement apply/cancel pattern
rancher-sandbox/rancher-desktop pull request #2517
Opened 2022-07-11 18:34 UTC by rak-phillip

This implements the apply/cancel pattern by making use of a vuex store to track preferences from a central location. With this pattern in place, components are responsible solely for rendering preference data and emitting events when said data needs to be updated. 

We identified issue #2509, which will need to be resolved before merging this PR.

closes #2376

2022-07-11 21:53 UTC, mook-as requested changes

2022-07-11 22:26 UTC, rak-phillip commented on src/pages/Preferences.vue
> +      await this.$store.dispatch(
We could introduce a watcher that will invoke `applyPreferences` only when credentials has a value. I originally wanted to await getting credentials, but there wasn't really a good way that I could find to do so with ipc/events..

2022-07-11 22:27 UTC, rak-phillip commented on src/pages/Preferences.vue
> +        }
This is true. In hindsight, it's all so obvious 😅

2022-07-11 22:32 UTC, rak-phillip commented on src/window/preferences.ts
> +          'Cancel'
I think `Discard changes` fits better here, thanks!

2022-07-11 22:33 UTC, rak-phillip commented on src/components/Preferences/ApplicationBehavior.vue
> +      type:     Object,
It's very possible 😁

2022-07-11 22:34 UTC, rak-phillip commented on src/components/Preferences/ApplicationBehavior.vue
> +      return !this.preferences?.kubernetes?.suppressSudo || false;
Agreed, thanks!

2022-07-11 22:36 UTC, rak-phillip commented on src/components/Preferences/ApplicationBehavior.vue
> +      this.$store.dispatch('preferences/updatePreferencesData', { property, value });
Yeah, this definitely could be improved upon. As it stands, this is quite fragile and breaks without much warning if properties in Settings are renamed..

2022-07-12 17:33 UTC, rak-phillip commented on src/pages/Preferences.vue
> +      await this.$store.dispatch(
After taking a closer look, I don't think the watcher makes sense..

We only assign credentials and attempt `fetchPreferences` when we receive the `api-credentials` event. We use the same credentials for any subsequent calls.

I think what would make more sense is for us to make sure that we have an error state for when we're unable to fetch credentials or preferences and supply a mechanism to retry in the event of a failure.

2022-07-12 17:44 UTC, rak-phillip commented on src/pages/Preferences.vue
> +      await this.$store.dispatch(
Created #2522 to track this work

2022-07-12 17:59 UTC, mook-as requested changes
Looks good generally, we can do things in follow ups.

Only issue is that the Kubernetes port number turns into a string in the Vuex state (so that it looks like it has changes to apply if you change the port number and back).

2022-07-12 20:02 UTC, mook-as approved these changes
LGTM; I think I can get the port to be `null`, but that needs backend help to reject invalid settings.

2022-07-13 01:18 UTC, merged