Rename Factory Reset option to "Keep cached kubernetes images"
rancher-sandbox/rancher-desktop pull request #2578
Opened 2022-07-19 21:12 UTC by jandubois

because "Container System Images" is kind of abstract? What are they, and why would you or wouldn't you want to keep them?

See also https://github.com/rancher-sandbox/rancher-desktop/issues/2494#issuecomment-1189536627

2022-07-19 22:05 UTC, ericpromislow requested changes
I assume you want to change the wording in https://github.com/rancher-sandbox/rancher-desktop/blob/658b62e498c2b450a33148f5e14bb1c8df7d2325/src/go/rdctl/cmd/factoryReset.go#L37 to be consistent with this.

Note that in the UI the default is to remove the cached images, and on the command-line the default is to keep them.

2022-07-20 05:35 UTC, jandubois commented
> I assume you want to change the wording in
> 
> https://github.com/rancher-sandbox/rancher-desktop/blob/658b62e498c2b450a33148f5e14bb1c8df7d2325/src/go/rdctl/cmd/factoryReset.go#L37
> 
> to be consistent with this.
> Note that in the UI the default is to remove the cached images, and on the command-line the default is to keep them.

Yeah, I don't know. The fact that the defaults are not the same already seems confusing, so I decided to leave it alone for now. I still expect to rename a lot of `rdctl` commands and options when we go to the `v1` API and make it non-experimental.

But yeah, I guess I'll change "system images" to "cached kubernetes images" everywhere, for some level of consistency.

2022-07-20 05:41 UTC, jandubois commented
And it is getting worse by `wsl-helper factory-reset` having a `--keep-system-images` option, while `rdctl factory-reset` has `--remove-kubernetes-cache`. 🙍 

At least `wsl-helper` should not be exposed to the user, so I'll leave this alone for now.

2022-07-20 21:07 UTC, ericpromislow commented on src/pages/Troubleshooting.vue
> +            :options="[{id: 'keepImages', label: 'Keep cached kubernetes images'}]"
`Kubernetes` should be capitalized, but I'm fine not capitalizing the other two words.

2022-07-21 18:45 UTC, ericpromislow approved these changes

2022-07-21 18:46 UTC, merged