Move keep cached images option to message box
rancher-sandbox/rancher-desktop pull request #2606
Opened 2022-07-21 23:17 UTC by rak-phillip

This moves the "Keep cached images" option to the Factory Reset dialog. This pattern is consistent with the Reset Kubernetes dialog and keeps the actions on the page right-aligned. 

closes #2494 

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>

2022-07-22 00:04 UTC, ericpromislow commented
It's ok, but I'm not thrilled with a big block of centered text. How much trouble is it to build a custom dialog box with left-aligned text?

2022-07-22 01:04 UTC, rak-phillip commented
> It's ok, but I'm not thrilled with a big block of centered text. How much trouble is it to build a custom dialog box with left-aligned text?

We can look at dropping the native dialogs here. I believe this centered design has been the default since big sur..

2022-07-22 18:35 UTC, ericpromislow requested changes
Requesting the alternative code that doesn't center the text body.

2022-07-22 21:15 UTC, ericpromislow commented on src/assets/translations/en-us.yaml
> +        detail: <p>Doing a factory reset will remove your cluster and all Rancher Desktop settings, and shut down Rancher Desktop. If you intend to continue using Rancher Desktop, you will need to ma
Verifying the HTML markup is rendered correctly. But I would reword "Are you sure you want to factory reset?" as "Are you sure you want to reset everything?"

2022-07-22 21:15 UTC, ericpromislow requested changes
Yes, this is better. There are some minor problems, but they should go into a separate issue:

On linux, the dialogs for "Factory Reset" and "Reset K8s" come up immediately, and look great.

On macOS, I can see the dialogs resize as the text is rendered, but they look fine after.

On Windows, for both buttons, the dialogs appear to blink when they're created (shows up, disappears, and then shows up right after and stays), and there's extra white space under the text.

This should be verified and covered in another issue, for the next release.

2022-07-22 23:46 UTC, ericpromislow approved these changes
OK. Needs some cosmetic work on (my) Mac and Windows boxes. For later.

2022-07-22 23:46 UTC, merged

2022-07-23 02:26 UTC, rak-phillip commented
@ericpromislow I'm not able to reproduce the behavior described in Windows. I might need more information to properly address (video taken from `main` after merge of this PR)

https://user-images.githubusercontent.com/835961/180587131-c60c6d3f-725a-4add-9ba9-a011e4ac11d9.mp4