Add support for named pipes
rancher-sandbox/rancher-desktop pull request #2770
Opened 2022-08-17 17:06 UTC by Nino-K

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-08-17 23:07 UTC, mook-as requested changes
I was unable to run the tests due to a crash; please it (identified) and we can try again.

2022-08-17 23:07 UTC, mook-as commented on src/go/vtunnel/test/e2e/connectivity_test.go
> +	installCmd := cmdExec(
Do we need `installCmd` (as opposed to `cmdExec(…).Run()` directly)?

2022-08-17 23:07 UTC, mook-as commented on src/go/vtunnel/test/e2e/connectivity_test.go
> +	timeout := time.Second * 20
Given that we're just polling in a loop, the timeout length is probably irrelevant — even going to a full minute is fine.

2022-08-17 23:07 UTC, mook-as commented on src/go/vtunnel/test/e2e/connectivity_test.go
> +		time.Sleep(time.Second * 2)
Please add a comment on this sleep.

2022-08-23 18:58 UTC, mook-as approved these changes

2022-08-23 18:58 UTC, merged

2022-09-21 16:20 UTC, Nino-K commented
https://github.com/rancher-sandbox/rancher-desktop/issues/2677