Update Alpine Lima ISO to 0.2.21
rancher-sandbox/rancher-desktop pull request #2894
Opened 2022-09-12 16:09 UTC by ryanfb

Because this release incorporates lima-vm/alpine-lima#84, this should fix #2771

2022-09-12 16:11 UTC, jandubois approved these changes
Thanks, LGTM

2022-09-12 16:13 UTC, jandubois commented
Note that #2864 should be addressed before this PR is merged

2022-09-12 16:46 UTC, jandubois requested changes
Please fix linter complaints.

Also wait for a new WSL-distro release to keep the Windows version in sync with the macOS/Linux one. I've just created https://github.com/rancher-sandbox/rancher-desktop-wsl-distro/pull/49. Once it is merged, I will create a new release there as well.

2022-09-12 16:48 UTC, jandubois commented
> Please fix linter complaints.

I'm sorry, the linter errors are not due to your PR; will have to be fixed in main, and then you have to rebase. Not sure how this could happen.

2022-09-12 17:12 UTC, ryanfb commented
> > Please fix linter complaints.
> 
> I'm sorry, the linter errors are not due to your PR; will have to be fixed in main, and then you have to rebase. Not sure how this could happen.

Happy to rebase and push once #2895 is merged.

2022-09-12 18:35 UTC, jandubois commented
> Happy to rebase and push once #2895 is merged.

This is not necessary; sorry I was severely confused earlier.

However, we do want the WSL-distro changes included in this PR, to keep it in sync with alpine-lima. I think I've sorted this out now, and will ping you here once we have a new release for WSL-distro.

2022-09-13 01:46 UTC, jandubois commented
> will ping you here once we have a new release for WSL-distro.

I've made a WSL-distro release with the corresponding changes and pushed an extra commit to your PR to bump that image as well. Will merge if CI ends up being green (which it should).

2022-09-13 01:47 UTC, jandubois approved these changes
Thanks!

2022-09-13 02:52 UTC, merged