Enable Privileged Services
rancher-sandbox/rancher-desktop pull request #2950
Opened 2022-09-20 22:54 UTC by Nino-K

This will allow us to start RD guest agent with the correct parameters when privileged service is installed.

Signed-off-by: Nino Kodabande <nkodabande@suse.com>

2022-09-20 23:15 UTC, ericpromislow commented on src/backend/wsl.ts
> +    let privilegedServiceEnabled;
`privilegedServiceEnabled` is never set to true. Is there supposed to be a config on this?

2022-09-20 23:17 UTC, ericpromislow commented on src/backend/wsl.ts
> +    const kube = K3sHelper.requiresPortForwardingFix(kubeVersion);
Not part of this PR strictly speaking, but `kube` isn't a great name. Better to make this `addKubernetesSupport` or whatever `GUESTAGENT_KUBERNETES` means.

2022-09-20 23:20 UTC, ericpromislow requested changes
One rename request, one error.

2022-09-20 23:36 UTC, Nino-K commented
@ericpromislow PTAL, I think our CI is acting up 🤔

2022-09-20 23:52 UTC, ericpromislow requested changes
lint error:
```
[error] ERROR in src/backend/wsl.ts:1140:120
TS2345: Argument of type 'RecursiveReadonly<RecursiveReadonly...
```

2022-09-21 00:29 UTC, ericpromislow approved these changes
It works now. Trying to run `privileged-service.exe start` fails; I assume that's out of scope for this PR.

2022-09-21 00:43 UTC, merged

2022-09-21 16:18 UTC, Nino-K commented
https://github.com/rancher-sandbox/rancher-desktop/issues/2677