Don't show memory/CPU changes on Windows
rancher-sandbox/rancher-desktop pull request #301
Opened 2021-05-14 23:04 UTC by ericpromislow

- We don't configure the WSL metrics, so don't show exogenic changes.

Signed-off-by: Eric Promislow <epromislow@suse.com>

2021-05-14 23:28 UTC, mook-as requested changes

2021-05-14 23:28 UTC, mook-as commented on src/pages/K8s.vue
> +    if (!os.platform().startsWith('win')) {
```suggestion
    if (!this.hasSystemPreferences) {
```

2021-05-17 20:01 UTC, mattfarina approved these changes

2021-05-17 20:12 UTC, merged

2021-05-17 20:12 UTC, mattfarina commented
mook-as unavailable for a review so merging. His comment was addressed.