Move diagnostics run to before main window is opened in `Electron.app.whenReady` handler
rancher-sandbox/rancher-desktop pull request #3051
Opened 2022-09-28 22:39 UTC by adamkpickering

Fixes #3044.

If this works for Jan, that is.

2022-09-29 17:54 UTC, ericpromislow commented on background.ts
> +    await diagnostics.runChecks().catch(console.error);
I'm not sure you can combine `await` and the `catch` method. Better to do this:
```
try {
  await diagnostics.runChecks();
} catch(ex: any) {
  console.error(ex);
}
```

2022-09-29 17:54 UTC, ericpromislow requested changes
Better to use await with a `try...catch`.

2022-09-29 18:45 UTC, jandubois commented
> If this works for Jan, that is.

Didn't work for me :(

2022-09-30 17:08 UTC, jandubois commented
Obsolete; issue has been fixed by #3060

2022-09-30 17:08 UTC, closed without merging