Add initial support for Windows Installer.
rancher-sandbox/rancher-desktop pull request #3285
Opened 2022-10-26 01:23 UTC by mook-as

For ease of development, this is currently an extra command (`npm run wix`) that is run separately from `npm run build`.  This will be changed in the future once the MSI build machinery is complete and we can replace the current NSIS-based one.

As with all installer changes, it is recommended to test the resulting installer in a VM that can be rolled back.

2022-10-26 21:30 UTC, Nino-K requested changes
Left some comments that require clarification.

2022-10-26 22:14 UTC, mook-as reviewed
Forgot to enable linting `*.tsx`; that has now been fixed.

Made an extra commit, but we should squash before merging — that commit isn't worth being separate on merge.

2022-10-28 17:57 UTC, Nino-K submitted a review, later dismissed
LGTM

2022-10-31 17:30 UTC, Nino-K approved these changes

2022-10-31 18:57 UTC, merged