WiX: Clarify when elevation is needed for WSL.
rancher-sandbox/rancher-desktop pull request #3439
Opened 2022-11-22 22:22 UTC by mook-as

- Use our own install scope dialog, so that we can move the per-machine install option to the top, with custom text describing the additional features we get in that case.
- Use our own verify ready dialog, with custom text when we need to force an admin install in order to install WSL.
- Given the custom dialogs, we no longer need to override the default dialog flow (avoiding potential issues when doing repair/etc. flows).

2022-11-23 00:37 UTC, ericpromislow commented on build/wix/scope.wxs
> +  - This describes the install scope dialog; we are custimizing this one to
typo: `customizing`.

2022-11-23 00:38 UTC, ericpromislow commented on build/wix/scope.wxs
> +  - emphaisize per-machine installation, as that is required for privileged
typo: `emphasize`

2022-11-23 00:40 UTC, ericpromislow commented on build/wix/string-overrides.wxl
> +  <String Id="InstallScopeDlgPerUserDescription">[ProductName] will be installed in a per-user folder and be available just for your user account. You do not need local Administrator privileges. This
`and required` should just be `require` to be consistent with the rest of the sentence.

2022-11-23 00:41 UTC, ericpromislow commented on build/wix/string-overrides.wxl
> +  <String Id="VerifyReadyDlgKernelInstallText" Overridable="yes">[ProductName] will be installed installed in a per-machine folder and be available for all users. This enables listening on non-loopba
`installed installed` hiccup.

2022-11-23 01:07 UTC, ericpromislow requested changes
Works fine, but there are some typos in the text.

2022-11-23 22:30 UTC, mook-as commented
Amended the commit, as the changes do not affect any logic (hopefully).

2022-11-24 19:24 UTC, Nino-K approved these changes

2022-11-24 19:26 UTC, merged