Run fstrim /mnt/data during boot and before shutdown
rancher-sandbox/rancher-desktop pull request #3442
Opened 2022-11-23 01:12 UTC by jandubois

Only when using Lima. Releases unused space in the data volume back to the host. The call during boot is redundant and only useful when the VM was not shut down via the Rancher Desktop app.

2022-11-23 19:50 UTC, gaktive commented
@IsaSih to test on M1 and @adamkpickering to test on Linux.

2022-11-24 00:14 UTC, IsaSih commented
Tests passed on Mac M1. However, I noticed a new dialog requesting permission to change network configurations via limactl. Switched back to an older version of Rancher Desktop, and did not get this dialog.
<img width="254" alt="Screen Shot 2022-11-23 at 3 49 08 PM" src="https://user-images.githubusercontent.com/70187881/203667007-ace7d4c5-0a85-48bf-90c8-b8491366495e.png">

2022-11-24 21:58 UTC, adamkpickering requested changes
Looks like this doesn't reduce the size of the data volume on Linux. I started RD after a factory reset, and then did the following:
```
/home/adam> ls ~/.local/share/rancher-desktop/lima/0/diffdisk
 #                            name                             type    size     modified
 0   /home/adam/.local/share/rancher-desktop/lima/0/diffdisk   file   1.7 GiB   now
/home/adam> rdctl shell sh -c 'time head -c 4294967296 </dev/urandom >$HOME/random'
real    0m 30.49s
user    0m 16.73s
sys     0m 13.67s
/home/adam> ls ~/.local/share/rancher-desktop/lima/0/diffdisk
 #                            name                             type    size     modified
 0   /home/adam/.local/share/rancher-desktop/lima/0/diffdisk   file   5.6 GiB   now
/home/adam> rdctl shutdown
Shutting down.
/home/adam> ls ~/.local/share/rancher-desktop/lima/0/diffdisk
 #                            name                             type    size        modified
 0   /home/adam/.local/share/rancher-desktop/lima/0/diffdisk   file   5.7 GiB   11 seconds ago
```

2022-11-24 22:03 UTC, jandubois commented
> Looks like this doesn't reduce the size of the data volume on Linux.

The data volume is a sparse file. `ls` will always show the full file size. You must use `du` to show how much space the file is actually using on disk.

2022-11-24 22:39 UTC, adamkpickering approved these changes
It appears that this only works on macOS. However, it doesn't break anything on Linux, so we will address Linux later.

2022-11-24 22:47 UTC, merged