Bind mounts should be (re)created when request uses container name
rancher-sandbox/rancher-desktop pull request #3496
Opened 2022-11-30 08:08 UTC by wolfymaster

This change adds support for re-binding mounts when starting/stopping/restarting containers using the container's name.

One caveat is that the container must have been explicitly assigned a name at creation and not randomly assigned a name by docker. 

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/2231 

Signed-off-by: Paul Sherer <wolfy@wolfymaster.com>

2022-11-30 22:13 UTC, mook-as requested changes
Thank you for digging into the issue and submitting a PR!

Unfortunately, I don't think this quite fixes the issue: it's possible to refer to the container by using a unique prefix (IIRC) of the container id:

```
$ mkdir vol
$ date > vol/hello.txt
$ docker run -itd --restart=always -v $PWD/vol:/vol --name cc alpine
ccb7ffe80e2b85244ef2e3b85b24ec85333f73de26bee9ffd6fc93ab8b58c25d
$ docker exec -ti cc cat /vol/hello.txt
Wed 30 Nov 2022 01:55:22 PM PST
$ docker stop cc
cc
$ docker start cc
cc
$ docker exec -i cc cat /vol/hello.txt
Wed 30 Nov 2022 01:55:22 PM PST
$ docker stop cc
cc
$ docker ps -a
CONTAINER ID   IMAGE     COMMAND     CREATED         STATUS                       PORTS     NAMES
ccb7ffe80e2b   alpine    "/bin/sh"   4 minutes ago   Exited (137) 4 seconds ago             cc
$ docker start ccb7ffe80e2b
ccb7ffe80e2b
$ docker exec -i cc cat /vol/hello.txt
cat: can't open '/vol/hello.txt': No such file or directory
```

I think we'll have to [inspect the container](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerInspect) to convert the input string to the full container ID, and then look up the mount information via that full ID. Does that sound reasonable to you?

2022-11-30 22:42 UTC, wolfymaster commented
@mook-as Thanks for the feedback! Yes, I must admit that I was also aware of this and that the PR does not handle that case. A more complete solution is to do exactly what you stated and in a way, "resolve" the identifier provided to the full container id. My hesitancy toward that approach was the size of the change required to fix the original specific issue. 

I'm happy to revise this PR to take a stab at implementing that complete solution.

2022-11-30 22:47 UTC, mook-as commented
> I'm happy to revise this PR to take a stab at implementing that complete solution.

That sounds great — I'll monitor the PR† and re-review when I see the changes!

†Actually I just watch the whole repo so I get every message, but you get the idea :)

2022-12-01 16:17 UTC, ryancurrah commented
We just adopted Rancher Desktop at our organization and some of our Windows developers are running into this issue. Look forward to seeing this in the next release! Thank you.

2023-01-09 23:09 UTC, mook-as requested changes
Looks good, just some minor comments.

2023-01-10 00:07 UTC, wolfymaster commented on src/go/wsl-helper/pkg/dockerproxy/serve.go
> +	inspectURL := fmt.Sprintf("%s://%s%scontainers/%s/json", req.URL.Scheme, req.URL.Host, version, id)
I'd be fine with hardcoding a value. Do you have an opinion on where that should be declared? I'm not a fan of hardcoding within the string.

2023-01-10 00:09 UTC, wolfymaster commented on src/go/wsl-helper/pkg/dockerproxy/serve.go
> +func (m *requestMunger) InspectContainerRequest(req *http.Request, id string, dialer func() (net.Conn, error)) (*containerInspectResponseBody, error) {
ah.. yes. I understand the confusion. I like `CanonicalizeContainerID`. Thanks for that feedback! I appreciate it!

2023-01-10 00:12 UTC, mook-as reviewed
Forgot to mention it before — thanks a lot for working on this!

2023-01-10 00:12 UTC, mook-as commented on src/go/wsl-helper/pkg/dockerproxy/serve.go
> +	inspectURL := fmt.Sprintf("%s://%s%scontainers/%s/json", req.URL.Scheme, req.URL.Host, version, id)
Hmm, just as a `const` within the file? I don't expect us to want to change it very often.

2023-01-17 18:59 UTC, mook-as commented
Hi @wolfymaster! Just wanted to check how things are going. This PR is pretty close (just down to trivial changes), and we didn't want to miss the momentum :)

2023-01-17 19:36 UTC, wolfymaster commented
@mook-as yeah, I almost have everything buttoned up.

2023-01-20 20:23 UTC, mook-as commented
The E2E tests are failing because of:
```
2023-01-20T19:08:24.379Z: Kubernetes was unable to start: Error: /home/ranchertest/src/resources/linux/lima/bin/limactl exited with code 1
    at ChildProcess.<anonymous> (/home/ranchertest/src/dist/app/background.js:56096:27)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  stdout: '',
  stderr: 'time="2023-01-20T19:08:24Z" level=debug msg="interpreting argument \\"0\\" as an instance name"\n' +
    'time="2023-01-20T19:08:24Z" level=info msg="Using the existing instance \\"0\\""\n' +
    'time="2023-01-20T19:08:24Z" level=info msg="Attempting to download the image from \\"/home/ranchertest/src/resources/linux/alpine-lima-v0.2.25.rd2-rd-3.16.0.iso\\"" digest=\n' +
    'time="2023-01-20T19:08:24Z" level=fatal msg="failed to download the image, attempted 1 candidates, errors=[failed to download \\"/home/ranchertest/src/resources/linux/alpine-lima-v0.2.25.rd2-rd-3.16.0.iso\\": failed to open source /home/ranchertest/src/resources/linux/alpine-lima-v0.2.25.rd2-rd-3.16.0.iso: open /home/ranchertest/src/resources/linux/alpine-lima-v0.2.25.
```
Looking at the playwright trace logs, there _is_ one of our error dialogs.

But the build log contains:
```
Downloading https://github.com/rancher-sandbox/alpine-lima/releases/download/v0.2.25.rd2/alpine-lima-rd-3.16.0-x86_64.iso to /home/ranchertest/src/resources/linux/alpine-lima-v0.2.25.rd2-rd-3.16.0.iso...
```
So the file should have been downloaded. But I also notice in the diagnostics logs:
```
2023-01-20T19:08:24.190Z: Check RD_BIN_DOCKER_CLI_SYMLINK_DOCKER-COMPOSE.DOWNLOAD result: {"description":"The file `~/.rd/bin/docker-compose.download` is a symlink to `~/src/resources/linux/bin/docker-compose.download`, which is not executable.","passed":false,"fixes":[]}
```
So that sounds like we started downloading the file, and was somehow aborted without even doing the `finally` bit to to clean up, somewhere around https://github.com/rancher-sandbox/rancher-desktop/blob/8352cbf3877986e0ba44fdf5dd132e08e254b248/scripts/lib/download.ts#L75-L99

I _think_ we're good to override the CI here, but let me discuss with some of the other folks.

2023-01-20 21:33 UTC, mook-as commented
Discussed offline, we're going to merge this as-is, since the affected files shouldn't even be relevant for the tests that failed. (The changed code is Windows-only, and the failing test runs are only on Linux.)

2023-01-20 21:34 UTC, merged

2023-01-20 21:37 UTC, mook-as commented
Merged, thanks!

I've slapped the `release-note` label on in case we want to highlight external contribution in the release notes (I'm not actually what the normal thing there is, so that's not a guarantee that it will actually land in the release note).