Feature/3773
rancher-sandbox/rancher-desktop pull request #3826
Opened 2023-01-24 11:36 UTC by torchiaf

Fixes #3773

Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

2023-01-27 23:03 UTC, adamkpickering requested changes
Mainly need clarification on a few things. I wasn't able to try it on macOS - @jandubois would you mind giving it a shot? I'm particularly curious about when RD shows up in the dock.

2023-02-06 08:50 UTC, torchiaf commented on pkg/rancher-desktop/layouts/default.vue
> -    ipcRenderer.send('app-ready');
Yes, I think we should remove it.

2023-02-06 08:51 UTC, torchiaf commented on pkg/rancher-desktop/window/index.ts
> -export function openMain(showPreferencesModal = false) {
See comment below.

2023-02-06 08:56 UTC, torchiaf commented on pkg/rancher-desktop/window/index.ts
> -  if (showPreferencesModal) {
Yes, It's a cleanup that we should have been done in #3804

2023-02-06 08:59 UTC, torchiaf commented on pkg/rancher-desktop/window/preferences.ts
> -  app.dock?.show();
This is a bug. Since the Preferences dialog can be opened separately from the main, we have to show the RD icon. I'm reverting this line.

2023-02-06 09:04 UTC, torchiaf commented
Thanks Adam, I left some updates with requested changes.

2023-02-06 17:15 UTC, adamkpickering approved these changes

2023-02-06 18:56 UTC, merged