Move to v1 of the backend API
rancher-sandbox/rancher-desktop pull request #3891
Opened 2023-02-07 00:29 UTC by ericpromislow

All /v0 endpoints are now errors (except for the `/v0` endpoint which just returns an array containing itself).

Signed-off-by: Eric Promislow <epromislow@suse.com>

2023-02-09 00:14 UTC, mook-as submitted a review, later dismissed
I think we should land #3861 first, or at least do _something_ so people don't assume we intend to support v1, but 🤷

2023-02-09 05:24 UTC, ericpromislow commented
I assigned that other issue the `Next` milestone, and would rather get this merged when ready. Because a bunch of other PRs depend on this PR.

2023-02-10 19:39 UTC, jandubois commented
> I think we should land #3861 first, or at least do _something_ so people don't assume we intend to support v1, but 🤷

#3927 should be included in this release to inform users that the v1 API is still considered internal and experimental.

@mook-as Does this address your concerns? Feel free to update #3927 if you think additional notices are required.

2023-02-10 20:06 UTC, mook-as commented
FWIW, I preferred fixing #3927 _first_ so that we keep main always shippable (if this lands first, we should make sure that gets fixed before we ship).  That includes getting info into the hands of people (expected count: 0) who randomly pull `main` and play with it.

But that's certainly a preference that's not worth frustrating people too much with.

2023-02-10 21:59 UTC, ericpromislow commented
I think we should get this in first and write up any policy later.

2023-02-13 20:29 UTC, mook-as requested changes
Basically looks fine. Checked with `git grep -w v0 -- . ':!**/go.mod' ':!**/go.sum'`.

2023-02-14 18:15 UTC, ericpromislow commented on e2e/rdctl.e2e.spec.ts
> +    const telemetry = (await resp.json()).application.telemetry.enabled;
done

2023-02-14 19:20 UTC, merged