Add `--experimental.virtual-machine.mount.9p.*` settings
rancher-sandbox/rancher-desktop pull request #4043
Opened 2023-02-24 02:30 UTC by jandubois

🚧 Validation is still incomplete 🚧

This commit temporarily exports kubeBackend.k3sHelper so that we can call k3sHelper.requiresRestartReasons from the Lima backend.

All the requiresRestartReasons code should be moved to the BackendHelper instead.

2023-02-25 06:05 UTC, jandubois commented
Created #4055 to revert making `k3sHelper` public.

2023-02-27 21:32 UTC, mook-as requested changes

2023-02-27 21:46 UTC, jandubois commented on pkg/rancher-desktop/backend/k8s.ts
> +  readonly k3sHelper: K3sHelper;
See above:

> Created https://github.com/rancher-sandbox/rancher-desktop/issues/4055 to revert making k3sHelper public.

2023-02-27 22:39 UTC, jandubois commented on pkg/rancher-desktop/main/commandServer/settingsValidator.ts
> +        mergedSettings.experimental.virtualMachine.mount.type === MountType.NINEP;
No, the second half was based on a thinko; removed.

2023-02-27 22:40 UTC, jandubois commented on pkg/rancher-desktop/config/settings.ts
> +export enum MountType {
I don't think so, it is just for convenient that the values for `MountType` match the `mountType` value in `lima.yaml`. But the type is used in our own `Settings` structure.

2023-02-28 19:15 UTC, mook-as commented on pkg/rancher-desktop/config/settings.ts
> +export enum MountType {
Right, but those settings never make sense outside of lima, right? (In the current case, they don't make sense Windows; and ages ago, they don't make sense on minikube.)

2023-02-28 19:33 UTC, jandubois commented on pkg/rancher-desktop/config/settings.ts
> +export enum MountType {
Yeah, but if we ever have types that make sense on Windows, we would just add them. Adding them to a `LimaMountType` wouldn't make sense.

It is the job of the validator to filter out the settings that are not applicable to the current platform/architecture etc, but the types themselves should be a superset of all settings valid on any of the platforms.

As long as the fieldname is `virtualMachine.mount.type` I think the typename should be `MountType`. 

If the type was `LimaMountType` then I would expect the field name to be `mount.limaMountType` which means you would have to set it with `--experimental.virtual-machine.mount.lima-mount-type`, which I don't want.

2023-02-28 19:40 UTC, mook-as approved these changes
Looks fine, seems to work.

2023-02-28 19:42 UTC, merged