Code Signing on Windows, Try 2
rancher-sandbox/rancher-desktop pull request #405
Opened 2021-07-09 00:32 UTC by mook-as

This is a redo of #365, now that we have access to an actual code signing certificate and have a better idea of what we're doing.  Also, from the previous PR I've figured out that we can just manually sign the executables ahead of time to work around the electron-builder issue where it doesn't sign them itself.

Hopefully the [documentation](https://github.com/mook-as/rd/blob/code-signing-v2/docs/development/signing.md) provides enough information to test code signing.  I've rolled the previous suggestion in where they still make sense.

There should still be a follow-up for macOS notarization.

2021-07-15 23:22 UTC, ericpromislow requested changes
```
npm run sign -- '.\dist\Rancher Desktop-0.3.0-80-g92d000c-win.zip'
```
ran to completion with the FINGERPRINT setting from above. Apart from the typo in the comment the code looks good.

Rather than test this will this be used by the CI, so I can verify that I no longer get the untrusted-software prompt on a release build?

2021-07-15 23:22 UTC, ericpromislow commented on scripts/lib/sign-win32.ts
> +  // Sign indiviaul files.  See https://github.com/electron-userland/electron-builder/issues/5968
tyop: "individual"

2021-07-15 23:38 UTC, mook-as commented
(I will get to the fixes in a bit.)

No, the code signing _will not_ be used by CI; CI doesn't have access to our certificates:
- CI isn't under our control (they're GitHub-managed, Azure-hosted VMs)
- We don't really want the certificates to be always online; instead, we keep it airgapped.  Ideally, we'd have a dedicated machine (that is always offline) for signing.

2021-07-15 23:40 UTC, ericpromislow commented
Doh, wasn't thinking and was hoping that the CI would do the grunt work. But obviously not via github actions. We do have a CI for signing, it's just not automated (or very continuous, for that matter).

2021-07-26 22:23 UTC, ericpromislow approved these changes
Approving it again....

2021-07-26 22:26 UTC, merged