Change the location and name of the linux deployment profile files.
rancher-sandbox/rancher-desktop pull request #4206
Opened 2023-03-15 23:33 UTC by ericpromislow

They can't go in `~/.config/rancher-desktop` because they need to survive factory-resets (and uninstalls).

2023-03-15 23:36 UTC, jandubois commented on e2e/utils/TestUtils.ts
> +  const userProfilePath = path.join(paths.deploymentProfileUser, 'rancher-desktop.profile.json');
Shouldn't this be

```suggestion
  const userProfilePath = path.join(paths.deploymentProfileUser, 'rancher-desktop.defaults.json');
```

2023-03-15 23:38 UTC, ericpromislow commented on e2e/utils/TestUtils.ts
> +  const userProfilePath = path.join(paths.deploymentProfileUser, 'rancher-desktop.profile.json');
yes, guess that code isn't tested

2023-03-16 00:07 UTC, ericpromislow commented on e2e/utils/TestUtils.ts
> +  const userProfilePath = path.join(paths.deploymentProfileUser, 'rancher-desktop.profile.json');
changed

2023-03-16 00:11 UTC, jandubois commented on pkg/rancher-desktop/main/deploymentProfiles.ts
> +      profiles = readProfileFiles(configDir, basenames[0], basenames[1], JSON);
I find this easier to understand:

```suggestion
      const [defaults, locked] = linuxPaths[configDir];

      profiles = readProfileFiles(configDir, defaults, locked, JSON);
```

2023-03-16 00:13 UTC, jandubois reviewed
LGTM, but I have one stylistic request...

2023-03-16 00:34 UTC, jandubois requested changes
Please make the small change I requested (or tell me why that is not a good idea). Otherwise it looks fine to me.

2023-03-16 17:03 UTC, jandubois approved these changes
Thanks, LGTM

2023-03-16 18:43 UTC, merged