Bats readme
rancher-sandbox/rancher-desktop pull request #4328
Opened 2023-03-30 20:29 UTC by IsaSih

Created a readme providing documentation on the how to: setup, run, write and lint BATS tests

2023-03-31 17:02 UTC, jandubois requested changes
Thanks! I do have some change requests... 😄

2023-03-31 17:02 UTC, jandubois commented on bats/README.md
> +3. Please, make sure to fix the highlighted linting errors prior to submitting a PR. Not required, but highly recommendable. To do so, run the following command:
Fixing linter errors is **required** now; Github actions will fail if any errors are detected.

```suggestion
3. Please, make sure to fix the highlighted linting errors prior to submitting a PR. You can automatically apply formatting changes suggested by `shfmt` by running the following command:
```

2023-03-31 19:24 UTC, jandubois commented
Please also add a link from `docs/development/README.md` to `bats/README.md` (similar to the link for the screenshots README).

2023-04-01 00:41 UTC, IsaSih commented on bats/README.md
> +2. A Bats test file is a Bash script with special syntax for defining test cases. Under the hood, each test case is just a function with a description.
do you want me to remove it or to keep this as a simple brief intro the way it is?

2023-04-01 01:00 UTC, jandubois commented on bats/README.md
> +2. A Bats test file is a Bash script with special syntax for defining test cases. Under the hood, each test case is just a function with a description.
I would remove it unless you have some good argument why you want to keep it. It is not self-explanatory, so you still need to read the docs anyways. And we have plenty of tests that could work as an example.

Maybe have one example extensively documented, and then link to the actual test from here as a "recommended tutorial"? But maybe this should wait until later. Just get a README published, and then refine over time.

2023-04-03 21:29 UTC, jandubois requested changes

2023-04-03 21:29 UTC, jandubois commented on bats/README.md
> +BATS is a testing framework for Bash shell scripts that provides supporting libraries and helpers for customizable server-side test automation.
Not sure what "server-side" means here; Rancher Desktop is a desktop application.

```suggestion
BATS is a testing framework for Bash shell scripts that provides supporting libraries and helpers for customizable test automation.
```

2023-04-03 21:29 UTC, jandubois commented on bats/README.md
> +It's important to have a Rancher Desktop CI build installed with privileged rights before running the BATS tests.
Let's remove "with privileged rights" here, assuming it just means "installed for all users". I'll create a PR to fall back on a per-user installation if the system-wide location does not exist.

```suggestion
It's important to have a Rancher Desktop CI or release build installed before running the BATS tests.
```

2023-04-03 21:29 UTC, jandubois commented on bats/README.md
> +
I think you should explain that you need to clone the repo first.

Note that changing crlf settings is not necessary when you clone inside a WSL distro; it is only needed when you clone on Win32.

2023-04-03 21:29 UTC, jandubois commented on bats/README.md
> +1. To run the BATS test, specify the path to BATS executable from bats-core and run the following commands:
Sine you talk above about cloning the repo on Windows, you should also explain how to locate it inside a WSL distro on `/mnt/...`.

I see that happens in the 3rd example, but it does not explain that `/mnt/c` represents the `C:` drive from windows.

2023-04-03 23:59 UTC, IsaSih commented on bats/README.md
> +2. A Bats test file is a Bash script with special syntax for defining test cases. Under the hood, each test case is just a function with a description.
okay, I deleted the existing example and kept only the links to the documentation. I can elaborate a tutorial in a follow up PR

2023-04-04 18:00 UTC, gunamata approved these changes
LGTM

2023-04-04 18:21 UTC, jandubois approved these changes

2023-04-04 18:21 UTC, merged