RDX: Fix listImages for nerdctl
rancher-sandbox/rancher-desktop pull request #4443
Opened 2023-04-13 20:21 UTC by mook-as

There were issues with `listImages` when running with `nerdctl`, because it was emitting different output.

Also fixes an issue when re-running an already installed extension (e.g. on restart) because we added too many identical volumes.

2023-04-13 22:02 UTC, ericpromislow requested changes
Too many problems:

1. I installed the `Logs Explorer` but it doesn't show up in the `Extensions` sidebar on the left when I click on the `Extensions` nav button

2. When I click on  the `Installed` link in the `Extensions: Catalog | Installed` page, it loops

There are more `UnhandledPromiseRejectionWarning` messages in the main console than usual.

This is on macOS, running `npm run dev` with containerd

2023-04-14 05:42 UTC, jandubois commented
Since there is no issue for this PR, I put the PR itself on the board and in the 1.9 milestone for visibility.

@mook-as Does this have to go into 1.9, or can we move to 1.10 instead?

2023-04-14 17:26 UTC, mook-as commented
I don't think this needs to land in the tech preview (none of the whitelisted extensions work with nerdctl even after this is fixed).

2023-04-20 21:18 UTC, mook-as commented
Hmm, I've not been able to reproduce those issues. Logs Explorer installs fine on containerd (but doesn't work, because `nerdctl` doesn't implement the necessary flags).

Unfortunately, I'm not sure there's _any_ extension that this is visibly fixed by.  Updated the E2E tests so we can at least test that.

Not re-requesting review yet as this conflicts with #4514 now.

2023-04-22 01:39 UTC, mook-as commented
Requesting re-review, mostly so I can get logs on what's failing so we can fix them :)

2023-04-24 20:42 UTC, ericpromislow approved these changes
Looks ok

2023-04-24 20:42 UTC, merged