RDX: Image for testing host APIs
rancher-sandbox/rancher-desktop pull request #4523
Opened 2023-04-21 01:30 UTC by mook-as

This image is to be used for testing #4312

The test procedure would be something like:

1. Run `rdctl extension install ghcr.io/mook-as/rd/rdx-host-api-test`
2. Open the new extension
3. Click on "Open in web page" in the first section; it should open a browser.
4. (… other instructions dealing with clicking buttons)

This actually includes GitHub Actions to build the image in CI, publishing it into the repository's packages list (filtered on only when the image sources change).  This way we won't need the tester to build the image manually.  I believe we _shouldn't_ do this for the other variants (used in automated tests), because ensuring we test against the images in-tree (at the same commit we're testing) should be useful.

2023-04-21 01:30 UTC, mook-as commented on .github/workflows/rdx-host-api-tests.yaml
> +          linux/arm64
The addition of `arm64` is just to make it easier to test on M1 machines.

2023-04-21 19:44 UTC, ericpromislow requested changes
This needs a doc, probably in `bats/tests/extensions/README.md` on what to do with this change. The workflow file is too declarative (and I assume it contains some implicit assumptions) to let a poor reviewer quickly know what to do to see this change in action.

2023-04-22 00:55 UTC, mook-as commented
The workflow file just builds an image; there's no testing involved.

The PR description contains how to actually use the new image (which we'll later convert to a manual test case, since our automation tools can't deal with things external to the application).

2023-04-22 05:36 UTC, jandubois commented
> which we'll later convert to a manual test case, since our automation tools can't deal with things external to the applicatio

We should investigate if a UI scripting tool like https://sikulix.github.io can be used with Github actions to automate this.

I use https://www.keyboardmaestro.com/main/ myself for similar tasks, but it is commercial software and only works on macOS, whereas sikulix reportedly works on Windows and (some versions of) Linux too.

2023-04-24 17:20 UTC, mook-as commented
We should look into better automated testing, yes, but that's out of scope for this PR. (I'd also like to be able to test the installer; I was thinking [OpenQA](https://open.qa/) would be good for this to ensure we can test reboots.)

However, I'll mark both this comment and the previous one as off-topic.

2023-04-24 21:07 UTC, ericpromislow approved these changes
Looks ok, but I don't see how I can do any actual testing with this code. Approving, but leaving someone else to merge it

2023-04-24 21:50 UTC, merged