BATS: fix extensions/containers output
rancher-sandbox/rancher-desktop pull request #4541
Opened 2023-04-24 19:00 UTC by mook-as

In #4514, we now put the tag as the JSON body, rather than a literal `true`.  But the BATS test wasn't updated to match that.

Fixes an error from 1de9254eb5c5f40e9b595ca8e020569c4e700efa.

2023-04-24 22:46 UTC, ericpromislow requested changes
I'm seeing this error both before and after this PR, on both macos and linux:
```
bats bats/tests/extensions/containers.bats
 ✓ factory reset 
 ✓ start container engine 
 ✓ no extensions installed 
 ✓ build extension testing images 
 ✗ image - install
   (from function `rdctl' in file bats/tests/extensions/../helpers/commands.bash, line 76,
    in test file bats/tests/extensions/containers.bats, line 57)
     `rdctl api --method=POST "/v1/extensions/install?id=$(id vm-image)"' failed
   Internal Server Error
   {"message":"500 Internal Server Error"}
 ✗ image - check for running container
   (from function `assert_line' in file bats/tests/extensions/../helpers/../../bats-assert/src/assert_line.bash, line 219,
    in test file bats/tests/extensions/containers.bats, line 68)
     `assert_line --regexp "$(id vm-image).*[[:space:]]Up[[:space:]]"' failed
   
   -- no output line matches regular expression --
   regexp : rd/extension/vm-image.*[[:space:]]Up[[:space:]]
   output : CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES
   --
   
 ✓ image - uninstall 
 ✗ compose - install
   (from function `assert_output' in file bats/tests/extensions/../helpers/../../bats-assert/src/assert_output.bash, line 194,
    in test file bats/tests/extensions/containers.bats, line 85)
     `assert_output '"latest"'' failed
   Created
   
   -- output differs --
   expected : "latest"
   actual   : true
   --
   
 ✓ compose - check for running container 
 ✓ compose - uninstall 

10 tests, 3 failures
```

2023-04-25 17:27 UTC, mook-as commented
Please attach logs for the failures?

2023-04-25 19:52 UTC, ericpromislow commented
The PR still needs work when running both tests with `RD_CONTAINER_ENGINE=moby`

2023-04-26 23:51 UTC, mook-as commented
Merged into #4533 because BATS won't pass with either of the two PRs (they each fix some of the issues).

2023-04-26 23:51 UTC, closed without merging