Prevent mutex deadlock
rancher-sandbox/rancher-desktop pull request #4570
Opened 2023-04-27 20:47 UTC by Nino-K

Previously, the `removeAll` function was accruing the mutex lock and while holding on to the lock it would call `delete` function which also required the mutex lock. Therefore, this was causing a deadlock in the service that became unresponsive.

- Also, adds additional event logging to help with the debugging process.

2023-04-27 23:09 UTC, mook-as requested changes

2023-04-28 17:11 UTC, Nino-K commented on src/go/privileged-service/pkg/port/portproxy.go
> +	for _, proxy := range p.portMappings {
I don't think there is any point the process will exit right after this.

2023-04-28 17:34 UTC, Nino-K commented on src/go/privileged-service/pkg/port/portproxy.go
> +func execNetshDelete(port portProxy) error {
I added a comment above the mutex locks for `add` and `delete` functions to clarify why the lock is not wrapping the entire function.

2023-04-28 17:39 UTC, mook-as requested changes

2023-04-28 17:39 UTC, mook-as commented on src/go/privileged-service/pkg/port/portproxy.go
> +	for _, proxy := range p.portMappings {
In that case, we should adjust `Server#stop` to stop the listener _before_ calling `removeAll`.

2023-04-28 18:42 UTC, mook-as approved these changes

2023-04-28 20:34 UTC, merged