Ensure single instance of Vue is used with `npm link`
rancher-sandbox/rancher-desktop pull request #4759
Opened 2023-05-24 20:33 UTC by rak-phillip

This configuration sets up an alias for the vue package that points to the version of Vue installed in Rancher Desktop's `node_modules` directory. This ensures that only one instance of Vue is used during development.

After Rancher Dashboard upgraded to Vue 2.7, we started getting several errors in Rancher Desktop when using `npm link` with `@rancher/components`. Some of these errors include 

- `[Vue warn]: $attrs is readonly.`
- `[Vue warn]: $listeners is readonly.`

Setting up this alias helps to resolve issues involved in linking a library that targets Vue 2.7 in our project that targets Vue 2.6.

2023-05-25 10:40 UTC, torchiaf requested changes
I tested `npm link` before and after this change. It works, however I can still see some errors in my terminal.

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/26394656/3e1b9818-690c-41b7-a081-248c92b0551b)

Could you double check @rak-phillip  ?

2023-05-25 14:38 UTC, rak-phillip commented
> I tested npm link before and after this change. It works, however I can still see some errors in my terminal.

You'll find that it breaks in certain areas. Try navigating to a page that renders radio buttons, for example. 

I'll investigate and resolve the tsc warnings

2023-06-21 15:19 UTC, rak-phillip commented
@richard-cox give the above approach a try in Epinio. The `tsc` errors mentioned in this PR should not apply to other projects.

2023-06-21 17:44 UTC, richard-cox commented
@rak-phillip you're a star, that worked for us. I've added the alias to `shell/vue.config.js` in a branch that will make it in to `rancher/dashboard` `master` in 2.7q3. Will that impact this fix your side (do you just bring in the component?)

2023-06-21 18:21 UTC, rak-phillip commented
@richard-cox this should be fine. 

I was of the opinion that the consumer should specify this config, but I think applying the fix to shell will resolve the problem in a way that linking "just works". That alone makes it the right choice.

2023-06-26 20:02 UTC, rak-phillip commented
This change won't be required with the latest versions of `@rancher/shell`

2023-06-26 20:02 UTC, closed without merging