Get rid of PathManagementStrategy.NotSet
rancher-sandbox/rancher-desktop pull request #4928
Opened 2023-06-09 22:23 UTC by jandubois

It was introduced to help users upgrading from 1.3 to 1.4 (I think), which added the path management strategy setting as a replacement for putting symlinks into /usr/local/bin. Instead of the full first-run dialog we would display a simpler version that only asks about the value for the path management strategy.

This dialog has since been removed. If somebody will upgrade from 1.3 or earlier to 1.9 or later, then we'll default the strategy to RcFiles. This can still be changed in the preferences dialog later.

Fixes #4918

2023-06-09 22:31 UTC, mook-as requested changes
This is missing code to help people migrate if they previously had `notset`. (That shouldn't happen except on Windows, but it'll be easier down the road if we never have to remember "oh they can have it set to that other value".)

2023-06-09 22:31 UTC, mook-as commented on pkg/rancher-desktop/main/commandServer/settingsValidator.ts
> +    return desiredValue !== currentValue;
Given the simplification, we no longer need a specific `checkPathManagementStrategy` and can use `checkEnum` instead.

2023-06-09 23:08 UTC, mook-as requested changes

2023-06-09 23:08 UTC, mook-as commented on pkg/rancher-desktop/config/settings.ts
> +    for (; loadedVersion <= CURRENT_SETTINGS_VERSION; loadedVersion++) {
This would be easier if we just bumped it to version 8 instead. Otherwise on the next bump we'll get very confused.

2023-06-09 23:09 UTC, adamkpickering requested changes
This doesn't enforce the path management setting unless we go from `manual` to `rcfiles`. This is because the path management configuration is only enforced in the handler for the `mainEvents` `settings-update` event when the path management strategy changes.

It may be possible to fix this by enforcing the path management strategy every time the `settings-update` event is called, whether it has changed or not.

2023-06-10 00:56 UTC, mook-as approved these changes
LGTM, but it might be better to get Adam to take a second look?

2023-06-11 19:27 UTC, merged