Remove explicit call to rdctl shutdown
rancher-sandbox/rancher-desktop pull request #5107
Opened 2023-07-05 20:58 UTC by Nino-K

Currently teardown file has an explicit condition to calls rdctl shutdown on linux only. This will remove the condition to also call it on Windows.

2023-07-05 22:26 UTC, jandubois requested changes
It is not necessary to call it on macOS, so we should only do this on platforms that otherwise hang at the end of BATS.

2023-07-05 23:06 UTC, Nino-K commented
> It is not necessary to call it on macOS, so we should only do this on platforms that otherwise hang at the end of BATS.

Is calling it on macOS cause an error? Also, how does the app shutdown in macOS without calling the `rdctl shutdown`?

2023-07-06 03:01 UTC, jandubois commented
> Also, how does the app shut down in macOS

That's the thing: it doesn't. I prefer the app to stay running, so I can still inspect it after a test has failed. Every test starts with a factory-reset, which will force a shutdown anyways before the next test runs.

I don't know if we need to make this configurable; I'm afraid we are adding too many options though, so only want to do this if you think it is necessary.

2023-07-06 16:21 UTC, Nino-K commented
> so only want to do this if you think it is necessary.

I can say on Windows this is necessary, the tests will hang forever until the app is shut down either manually or through `rdctl shutdown`. Also, it looks as though, this was necessary on Linux too by the previous condition.

2023-07-06 17:43 UTC, ericpromislow commented
I've often run into this when running `containers/switch-engines.bats` on macOS, and it was fixed by adding `rdctl shutdown` in a final "test" in that bats file.

2023-07-06 19:12 UTC, jandubois approved these changes
Thanks, LGTM

2023-07-06 19:12 UTC, merged