Partially refactor `rdctl` factory reset code to use new `paths` package
rancher-sandbox/rancher-desktop pull request #5197
Opened 2023-07-19 17:22 UTC by adamkpickering

Related to #5062.

The need for this work became clear while I was working on the macOS and Linux snapshots backend (#5115). It doesn't use `paths.Paths` in every place it should, just the places that are most important for #5115. The rest of the refactoring can be done when there is less time pressure.

2023-07-20 22:07 UTC, ericpromislow commented
I'm now confused by the overlap between the `paths` and `directories` packages.

Also, `paths_windows.go` should probably use the `getKnownFolder` technique with packaged windows identifiers that `directories_windows.go` uses . For example, shouldn't the code in `factory_reset_windows.go` use the paths object ?

2023-07-20 22:07 UTC, ericpromislow requested changes
Looks like we can do more refactoring.

2023-07-21 18:00 UTC, adamkpickering commented
As I said in the body of this PR:

> It doesn't use paths.Paths in every place it should, just the places that are most important for https://github.com/rancher-sandbox/rancher-desktop/issues/5115. The rest of the refactoring can be done when there is less time pressure.

If you'd prefer that the refactoring be done all at once, we should close this PR and I can do my best to make some clean additions to the factory reset code for #5115.

2023-07-21 20:21 UTC, ericpromislow requested changes
Windows unit tests are failing:
```
PS C:\Users\eric\rancher-desktop\src\go\rdctl> go test .
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl [no test files]
PS C:\Users\eric\rancher-desktop\src\go\rdctl> go test ./...
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl [no test files]
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/cmd     [no test files]
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/autostart   [no test files]
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/config      [no test files]
# github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/factoryreset
pkg\factoryreset\factory_reset_windows.go:154:5: github.com/sirupsen/logrus.Debugf does not support error-wrapping directive %w
ok      github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/directories 0.295s
FAIL    github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/factoryreset [build failed]
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/options/generated   [no test files]
--- FAIL: TestGetPaths (0.00s)
    --- FAIL: TestGetPaths/should_return_correct_paths_without_environment_variables_set (0.00s)
        paths_windows_test.go:41: Actual paths does not match expected paths
            Actual paths: paths.Paths{AppHome:"C:\\Users\\eric\\AppData\\Roaming\\rancher-desktop", AltAppHome:"C:\\Users\\eric\\AppData\\Roaming\\rancher-desktop", Config:"C:\\Users\\eric\\AppData\\Roaming\\rancher-desktop", Logs:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\logs", Cache:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\cache", WslDistro:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\distro", WslDistroData:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\distro-data", Lima:"", Integration:"", Resources:"fakePath", DeploymentProfileSystem:"", DeploymentProfileUser:"", ExtensionRoot:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\extensions"}
            Expected paths: paths.Paths{AppHome:"C:\\Users\\eric\\AppData\\Roaming", AltAppHome:"C:\\Users\\eric\\AppData\\Roaming", Config:"C:\\Users\\eric\\AppData\\Roaming\\rancher-desktop", Logs:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\logs", Cache:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\cache", WslDistro:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\distro", WslDistroData:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\distro-data", Lima:"", Integration:"", Resources:"fakePath", DeploymentProfileSystem:"", DeploymentProfileUser:"", ExtensionRoot:"C:\\Users\\eric\\AppData\\Local\\rancher-desktop\\extensions"}
    --- FAIL: TestGetPaths/should_return_correct_paths_with_environment_variables_set (0.00s)
        paths_windows_test.go:75: Actual paths does not match expected paths
            Actual paths: paths.Paths{AppHome:"C:\\Users\\eric\\mockAppData\\rancher-desktop", AltAppHome:"C:\\Users\\eric\\mockAppData\\rancher-desktop", Config:"C:\\Users\\eric\\mockAppData\\rancher-desktop", Logs:"C:\\Users\\eric\\mockRdLogsDir", Cache:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\cache", WslDistro:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\distro", WslDistroData:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\distro-data", Lima:"", Integration:"", Resources:"fakePath", DeploymentProfileSystem:"", DeploymentProfileUser:"", ExtensionRoot:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\extensions"}
            Expected paths: paths.Paths{AppHome:"C:\\Users\\eric\\mockAppData\\rancher-desktop", AltAppHome:"C:\\Users\\eric\\mockAppData\\rancher-desktop", Config:"C:\\Users\\eric\\mockAppData\\rancher-desktop", Logs:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\logs", Cache:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\cache", WslDistro:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\distro", WslDistroData:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\distro-data", Lima:"", Integration:"", Resources:"fakePath", DeploymentProfileSystem:"", DeploymentProfileUser:"", ExtensionRoot:"C:\\Users\\eric\\mockLocalAppData\\rancher-desktop\\extensions"}
FAIL
FAIL    github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/paths       0.285s
ok      github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/reg 0.266s
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/shutdown    [no test files]
?       github.com/rancher-sandbox/rancher-desktop/src/go/rdctl/pkg/utils       [no test files]
FAIL
PS C:\Users\eric\rancher-desktop\src\go\rdctl>
```

2023-07-24 18:49 UTC, ericpromislow requested changes
A line I wrote last Dec. needs fixing because no one ever tried running unit tests on some Windows boxes before:
```
output, err := exec.Command("grep", append([]string{"-l", "MANAGED BY RANCHER DESKTOP"}, filenames...)...).CombinedOutput()
```

It needs to not use `grep` - just load each file, and use std Go code to check for the occurrence of the `MANAGED` string.

The `grep` test is also wrong because it will pass is any of the named files contain that line, but we want all of them to.

2023-08-01 20:56 UTC, ericpromislow approved these changes
looks good

2023-08-01 20:57 UTC, merged