BATS test for `ctrctl run --init`
rancher-sandbox/rancher-desktop pull request #5255
Opened 2023-07-30 21:28 UTC by jandubois

This requires that `/usr/bin/docker-init` and `/usr/bin/tini` exist (and are symlinks to `/sbin/tini-static`).

2023-08-01 20:48 UTC, ericpromislow approved these changes
Would it be better to have two separate tests, one for moby, one for nerdctl ?

2023-08-01 20:58 UTC, ericpromislow requested changes
Also I had to add a shutdown for `macos`

2023-08-01 21:02 UTC, jandubois commented
> Would it be better to have two separate tests, one for moby, one for nerdctl ?

No, all our tests are written so you run them with

```
RD_CONTAINER_ENGINE=containerd bats tests/...
RD_CONTAINER_ENGINE=moby bats tests/...
```

The difference between the container engines is just the name of the default `init` program, which is reflected in the regexp. Why would you want to create 2 almost identical tests? Keeping duplicated tests in sync just adds to our maintenance burden.

2023-08-01 21:03 UTC, jandubois commented
> Also I had to add a shutdown for `macos`

That is weird; it has never been necessary for any tests on macOS for me. How exactly did you run the test?

2023-08-23 00:05 UTC, jandubois commented
> Happens when I run either a dev run or the app installed in `/Applications/`

I could reproduce the issue with `RD_LOCATION=dev` but not with `RD_LOCATION=system`.

This is not really related to this PR, but I've added a commit to address the `dev` case.

The condition in `teardown_file` is getting a bit silly now, and it may be better to unconditionally call `rdctl shutdown` instead, but for now I like to keep this as a reminder to revisit the issue again in the future. We should be able to properly detach the Rancher Desktop background process and still have BATS terminate normally.

2023-08-23 19:36 UTC, ericpromislow approved these changes
Everything works fine now, looks good

2023-08-23 20:21 UTC, merged