SortableTable: Add padding to show box shadow on top
rancher-sandbox/rancher-desktop pull request #5362
Opened 2023-08-18 13:57 UTC by s0nea

Add padding to show the box shadow on top of the filter input field.

Before:
![Screenshot_2023-08-18_15-36-51](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/9a8a86cc-64d0-43a2-a541-7ed5dafe5934)

After:
![Screenshot_2023-08-18_15-37-21](https://github.com/rancher-sandbox/rancher-desktop/assets/8761082/0713798b-1e0c-474d-9cc2-7b4143e9e5ca)

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/3175

2023-08-18 17:14 UTC, rak-phillip requested changes
I think that we need to find a different location to apply this style

2023-08-18 17:14 UTC, rak-phillip commented on pkg/rancher-desktop/components/SortableTable/index.vue
> +  padding: 1px 0 20px 0;
We might not want to add the padding directly within SortableTable, as it is copied over from Rancher Dashboard and we run the risk of reverting this change if we update SortableTable again in the future.

Reference: #2200

2023-08-18 17:25 UTC, ericpromislow commented
I don't see any difference in light mode.
```
$ git diff main
diff --git a/pkg/rancher-desktop/components/SortableTable/index.vue b/pkg/rancher-desktop/components/SortableTable/index.vue
index 09170150..19d73f8b 100644
--- a/pkg/rancher-desktop/components/SortableTable/index.vue
+++ b/pkg/rancher-desktop/components/SortableTable/index.vue
@@ -1284,7 +1284,7 @@ $spacing: 10px;
 }

 .fixed-header-actions {
-  padding: 0 0 20px 0;
+  padding: 1px 0 20px 0;
   width: 100%;
   z-index: z-index('fixedTableHeader');
   background: transparent;
```

2023-08-18 17:26 UTC, ericpromislow commented
![Screen Shot 2023-08-18 at 10 25 20 AM](https://github.com/rancher-sandbox/rancher-desktop/assets/108392/580115a3-15ed-477f-9c58-8f920202a951)

2023-08-18 17:26 UTC, ericpromislow requested changes
Doesn't work in light mode

2023-08-28 13:27 UTC, s0nea commented
> Doesn't work in light mode

Thank you for testing @ericpromislow. I tested it in the light mode and it works on my env as well. I have the feeling it depends on the OS (-settings). Did you test it on macOS?

2023-08-28 21:16 UTC, ericpromislow approved these changes
It's ok now. I don't know what the problem was before -- maybe the wrong PR?

2023-08-28 23:28 UTC, rak-phillip approved these changes

2023-08-28 23:28 UTC, merged