backend/moby client: always set DOCKER_HOST for copy
rancher-sandbox/rancher-desktop pull request #5402
Opened 2023-08-25 23:54 UTC by mook-as

We previously ended up calling the docker CLI directly (instead of going through the wrapper that would correctly set DOCKER_HOST); this caused issues if the default context wasn't ours.

Fixes #5397

2023-08-28 21:02 UTC, ericpromislow commented
Could you add a bats test like this:
```
load '../helpers/load'

local_setup() {
    if ! using_docker; then
        skip 'Testing different docker contexts requires running docker'
    fi
}

@test 'factory reset' {
    factory_reset
}

@test 'start container engine' {
    RD_ENV_EXTENSIONS=1 start_container_engine
    wait_for_container_engine
}

@test 'installs with a different docker context' {
    run docker context ls
    assert_success
    assert_output --partial 'rancher-desktop *'
    run docker context use default
    assert_success
    run rdctl extension install prakhar1989/dive-in
    assert_success
    run rdctl extension list
    assert_success
    assert_output --partial 'prakhar1989/dive-in'
    run rdctl extension uninstall prakhar1989/dive-in
    assert_success
    assert_output 'Uninstalling image prakhar1989/dive-in: Deleted prakhar1989/dive-in'
}
```

2023-08-28 21:02 UTC, ericpromislow requested changes
Works fine, but should have a test (which fails on `main` but passes on this branch).

2023-08-28 22:41 UTC, mook-as commented
Rather than doing that, I just modified the existing BATS test to add an invalid docker context (and force cleanup on done).

(One sec while I make it draft again — it looks like the cleanup isn't correct)

2023-08-28 22:53 UTC, jandubois commented
> Rather than doing that, I just modified the existing BATS test to add an invalid docker context (and force cleanup on done).

Note that in #5395 we want to do this globally for all BATS tests.

2023-08-29 01:00 UTC, jandubois commented on bats/tests/extensions/containers.bats
> +    docker context create bats-invalid-context --docker 'host=tcp://invalid.test:99999'
It is a bit more robust to remove a left-over context here instead if relying on `teardown_file` to have cleaned it up before:

```
    run docker context rm bats-invalid-context
    assert_nothing
```

2023-08-29 20:01 UTC, jandubois approved these changes
Thanks, LGTM

2023-08-29 20:02 UTC, merged