Feature/5619 update electron
rancher-sandbox/rancher-desktop pull request #5620
Opened 2023-09-29 16:49 UTC by rak-phillip

2023-10-05 19:24 UTC, rak-phillip commented
We won't merge this until after the 1.11 release, but I think that this PR is in a state that is ready to review. Please note that the required node version has been updated to 18.16.x and we might need to reinstall yarn depending on how you manage your node versions.

2023-10-05 23:58 UTC, mook-as requested changes
Looks mostly fine, just some details and changes to commit messages.

2023-10-05 23:58 UTC, mook-as commented on package.json
> +    "node": ">=18.16"
Please update `README.md` to say this node version. (There are multiple places within that file.)

2023-10-05 23:58 UTC, mook-as commented on pkg/rancher-desktop/utils/protocols.ts
> +  // eslint-disable-next-line deprecation/deprecation
Please add a comment on why this is needed. You already have the follow-up filed as #5659 (thanks!), so maybe mention that too.

2023-10-05 23:58 UTC, mook-as commented on pkg/rancher-desktop/layouts/dialog.vue
> -  flex-flow: column;
It would be good to have more detail in the commit message about what this is fixing (that is, why this works).

2023-10-05 23:58 UTC, mook-as commented on pkg/rancher-desktop/window/index.ts
Again, more details in the commit message on what we're doing would help.

2023-10-05 23:58 UTC, mook-as commented on e2e/credentials-server.e2e.spec.ts
> +    const url = `http://127.0.0.1:${ serverState.port }/list`;
The commit message could mention things about not supporting IPv6.

2023-10-17 01:05 UTC, mook-as approved these changes
Seems to run (on Windows) and can still build the MSI installer.

2023-11-01 15:51 UTC, rak-phillip commented
@mook-as rebased on top of main. Let me know if your approval still stands. If so, I intend to merge as soon as is conveniently possible 🙂

2023-11-01 18:28 UTC, merged