Install limactl and lima-guestagent from rancher-desktop-lima repo
rancher-sandbox/rancher-desktop pull request #5718
Opened 2023-10-11 23:37 UTC by jandubois

And ignore the version bundled with lima-and-qemu. That way we can update lima independently from qemu (and *_vmnet daemons).

2023-10-12 20:02 UTC, ericpromislow requested changes
Fails on openSUSE:
```
$ yarn dev
```
==> limactl complains: `version GLIBC_2.32 not found` and the system can't start up.

2023-10-14 00:47 UTC, ericpromislow submitted a review, later dismissed
New failure on opensuse 15.5 (running go 1.21.3) when trying to enable kubernetes:
```
 msg="Using the existing instance \"0\""
2023/10/13 17:44:12 FATAL -- failed to create Watcher
goroutine 40 [running]:
runtime/debug.Stack()
/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/nxadm/tail/util.Fatal({0x100b927?, 0xc0006846c0?}, {0x0, 0x0, 0x0})
/home/runner/go/pkg/mod/github.com/nxadm/tail@v1.4.11/util/util.go:23 +0x8b
github.com/nxadm/tail/watch.(*InotifyTracker).run(0xc00069c000)
/home/runner/go/pkg/mod/github.com/nxadm/tail@v1.4.11/watch/inotify_tracker.go:220 +0x65
created by github.com/nxadm/tail/watch.glob..func1 in goroutine 39
/home/runner/go/pkg/mod/github.com/nxadm/tail@v1.4.11/watch/inotify_tracker.go:55 +0x14e
...
```

I'll attach the relevant logs. These look relevant

Commands:
$ gh pr checkout 5718
$ git clean -ffdx && yarn && yarn dev

2023-10-14 18:46 UTC, jandubois commented
> I'll attach the relevant logs.

There are no attached logs. I also see that E2E has now passed on CI.

@ericpromislow Please review the code changes, and approve if they look good. I think the problems running in a dev environment on openSUSE are unrelated to this PR.

2023-10-14 19:20 UTC, jandubois commented
I've pushed a version of this branch rebased on latest `main`, so I can use the CI build for integration testing.

It also updates `rancher-desktop-lima` to `0.18.0.rd2` because the previous release did not include the macOS `arm64` binaries (they were still compiled for `amd64` because `GOARCH` was not exported in the Github action).

There are no changes related to Linux in this latest update.

2023-10-16 21:22 UTC, merged