WSL: Unregister WSL distribution on factory reset.
rancher-sandbox/rancher-desktop pull request #590
Opened 2021-09-07 18:33 UTC by mook-as

Fixes #549.

Have to check if it's registered first, as otherwise WSL exits with `-1`.

2021-09-08 17:54 UTC, mattfarina commented
@mook-as There are some lint errors.

2021-09-09 21:46 UTC, ericpromislow requested changes
Looks good otherwise.

2021-09-09 21:46 UTC, ericpromislow commented on src/k8s-engine/wsl.ts
> +        stdio: ['ignore', await Logging.wsl.fdStream, await Logging.wsl.fdStream],
lint warnings

2021-09-10 16:38 UTC, ericpromislow submitted a review, later dismissed

2021-09-10 16:44 UTC, mook-as commented
Rebased due to merge conflicts.

2021-09-14 18:24 UTC, ericpromislow approved these changes
LGTM

2021-09-14 18:53 UTC, merged