Support code signing flow on mac
rancher-sandbox/rancher-desktop pull request #6019
Opened 2023-11-21 23:41 UTC by mook-as

This implements the `yarn sign *.zip` flow for macOS.

This would fix:
- #1021 
- #5909 (we have launch constraints, but it's unclear if that fixes #4867)
- #4091
- #5003 (it's already fixed, but this ensures no recurrence)

2023-11-23 00:09 UTC, ericpromislow reviewed
Code looks ok but I don't have any of the signing credentials to actually test it.

2023-11-25 00:28 UTC, jandubois requested changes
I only skimmed the list of entitlements so far, and it seems we need a few changes.

2023-11-25 00:28 UTC, jandubois commented on build/signing-config-mac.yaml
> +    - Contents/Resources/resources/darwin/lima/bin/qemu-system-aarch64
Not sure if you can add entries that may not exist, but we need to include qemu on amd64 as well:

```suggestion
    - Contents/Resources/resources/darwin/lima/bin/qemu-system-aarch64
    - Contents/Resources/resources/darwin/lima/bin/qemu-system-x86_64
```

2023-11-25 00:28 UTC, jandubois commented on build/signing-config-mac.yaml
> +    - com.apple.security.hypervisor
I think the `hypervisor` entitlement is only needed for qemu, but not for limactl.

2023-11-25 00:28 UTC, jandubois commented on build/signing-config-mac.yaml
> +    - com.apple.security.virtualization
I think qemu doesn't need `virtualization`, only limactl does. However, limactl should also get the `network.server` and `network.client` entitlements.

2023-11-25 00:31 UTC, jandubois commented on build/signing-config-mac.yaml
> +    - com.apple.security.virtualization
Just realized that only `limactl.ventura` does need `virtualization`, `network.server`, and `network.client`. The legacy `limactl` binary is only used on platforms that don't support VZ emulation.

2023-11-28 05:44 UTC, jandubois approved these changes
I have not reviewed the code beyond the list of granted entitlements, but I tested it by signing the aarch64 CI build of this PR with

```
yarn sign ~/Rancher\ Desktop-1.11.0-240-gc2c2c9c3-mac.zip
```

I've put both the signed DMG and the CI DMG from Github on Dropbox and downloaded it to a different M1 machine.

The signed binary executed correctly and showed the correct signature; the unsigned binary was rejected by Gatekeeper and refused to run. So this is looking good. I've not verified the individual entitlements on each executable.

I'm not sure if we want to remove the `com.apple.security.network.*` entitlements, as they should not be needed, and it would be good practice to only add the minimal number of entitlements needed.

One other minor issue is that the name of the signed file doesn't match the expected release name. The command above generated `Rancher\ Desktop-1.11.0-arm64.dmg` which still requires manual renaming to `Rancher.Desktop-1.11.0.aarch64.dmg`. This could be fixed in a separate PR though. And maybe the command could also generate the `sha512sum` file as well?

2023-11-28 05:44 UTC, jandubois commented on build/signing-config-mac.yaml
> +    - com.apple.security.network.client
I've checked why Lima has the `com.apple.security.network.server` and `com.apple.security.network.client` entitlements, and it turns out they were just copied from https://github.com/Code-Hex/vz/blob/bd29a7ea3d39465c4224bfb01e990e8c220a8449/example/linux/vz.entitlements, the library that Lima is using to implement VZ emulation.

I believe they are only needed for sandboxed App Store applications, so we can probably just remove them everywhere, to get a smaller set of entitlements.

2023-11-28 17:53 UTC, mook-as commented
Let's handle the follow-ups in #6071 so we can do some of the other things waiting on this PR.

2023-11-28 17:53 UTC, merged