Add --description-from-stdin and --description-from-file to `rdctl snapshot create`.
rancher-sandbox/rancher-desktop pull request #6120
Opened 2023-12-04 23:51 UTC by ericpromislow

Fixes #5881

2023-12-05 01:41 UTC, jandubois commented
Please fix indentation (run `make lint` inside the `bats` directory)!

2023-12-06 02:07 UTC, jandubois requested changes
Looks good and seems to work fine.

Still some (mostly) stylistic changes I would like to see.

2023-12-06 02:07 UTC, jandubois commented on src/go/rdctl/cmd/snapshotCreate.go
> +var snapshotDescriptionFromFile string
Since we shortened the option name, maybe we should shorten the variable name to match?

```suggestion
var snapshotDescriptionFrom string
```

2023-12-06 18:44 UTC, ericpromislow commented on bats/tests/snapshots/test-snapshot-list.bats
> +    TEMP=/tmp
I was searching for `TE?MP` using `git grep` to avoid `node_modules`, but because bats-lib is a submodule I didn't find that either.

2023-12-06 23:38 UTC, jandubois requested changes
Not sure if the `bats/README.md` changes belong into this PR, but if they stay, then they need to be correct.

2023-12-06 23:38 UTC, jandubois commented on bats/README.md
> +`TMP_DIR=$(wslpath_from_win32_env TMP_DIR)"`
The environment variable on Windows is `TMP` or `TEMP`, but not `TMP_DIR`.

```suggestion
`TMP_DIR=$(wslpath_from_win32_env TEMP)"`
```

2023-12-06 23:38 UTC, jandubois commented on bats/README.md
> +Use `$BATS_TMP_DIR` for temporary files. On Windows this needs to be converted to a wsl-compatible path
There is no `$BATS_TMP_DIR` variable.

```suggestion
Use `$BATS_FILE_TMPDIR` for temporary files. On Windows this needs to be converted to a wsl-compatible path
```

I would rather point to https://bats-core.readthedocs.io/en/stable/writing-tests.html#special-variables than to recommend a specific variable here. In general I don't think we should try to repeat the BATS docs, but rather point to the upstream docs instead.

2023-12-07 20:37 UTC, merged