Get snapshot title from lockfile during init
rancher-sandbox/rancher-desktop pull request #6140
Opened 2023-12-06 23:18 UTC by rak-phillip

This displays the `backend.lock` action if one exists during the Rancher Desktop init. 

This also does some additional refactoring so that the `backendIsLocked` variable is no longer global. The usage of the global variable makes it difficult to reason about when `backendIsLocked` would mutate. Now, if we want to inquire about the locked state, we utilize the function `doesBackendLockExist()`. 

## Screenshots

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/1a8d15e6-9eeb-406e-9156-c8fcd71cd8e2)

![image](https://github.com/rancher-sandbox/rancher-desktop/assets/835961/03af6e2a-bf06-4490-a772-adcdb19343c9)

2023-12-06 23:59 UTC, rak-phillip commented
@jandubois I'm requesting a review from you so that you can take a look and confirm that this behaves as expected.

2023-12-07 00:01 UTC, rak-phillip commented on pkg/rancher-desktop/layouts/default.vue
> +            header:          action || this.t('snapshots.dialog.generic.header', {}, true),
Thanks, we could probably just remove it at this point

2023-12-07 00:03 UTC, rak-phillip commented on pkg/rancher-desktop/layouts/default.vue
> +            header:          action || this.t('snapshots.dialog.generic.header', {}, true),
I updated the other instance of `ToDo` to read `TODO:`

2023-12-07 00:31 UTC, ericpromislow requested changes
I think there's a problem with the asynchness here. While RD is starting up, on the cmd line I run:
```
$ rdctl snapshot create s3
Cancelling snapshot creation...
Error: failed to create snapshot: Rancher Desktop state is STARTING. It must be fully running or fully shut down to perform the action: Creating snapshot "s3"
```

But the snapshot-creation thing shows up in the UI, although there's no lockfile. I need to shut down RD and restart it to make it work.

2023-12-07 17:04 UTC, rak-phillip commented
@ericpromislow thanks for testing, that was a good catch!

> I think there's a problem with the asynchness here.

I don't think it's an issue with the asynchronous nature of the code and has more to do with the fact that we emit `backend-locked-update` every time we check for a backend lock, which the original code did not do.

The issue should be fixed now, can you take another look?

2023-12-07 21:17 UTC, adamkpickering approved these changes
Looks good as far as I can tell :+1:

2023-12-08 00:30 UTC, ericpromislow approved these changes
Code looks ok

2023-12-08 00:30 UTC, merged