NSIS: Only elevate for WSL installation
rancher-sandbox/rancher-desktop pull request #632
Opened 2021-09-20 20:33 UTC by mook-as

This changes the Windows installer to only elevate the parts that need to install WSL.  This means people who normally use a non-privileged account (e.g. #613) will be able to work correctly.

This is a first pass — currently there's no indication ahead of time that we'll require elevation, and it's currently just popping up a PowerShell terminal for the installation.  I intend to attempt to get rid of at least the command prompt window while this is reviewed.

2021-09-21 17:46 UTC, mattfarina approved these changes
Tested and it works.

2021-09-21 18:32 UTC, mattfarina commented
Note, I removed my approval since there's a typo and it needs another code review. It worked in my testing though.

2021-09-21 21:10 UTC, ericpromislow requested changes
I ran into a problem here:
1. Created a non-admin user 'joe'
2. As admin user 'eric', uninstalled r-d and removed all AppData files
3. As admin user, built an installer and placed in c:/tmp/
4. Logged in as Joe, tried to install RD first time, and wsl.logs shows that it can't see any WSL distributions
5. Logged back in as eric, `wslconfig /l` shows both `ubuntu` and `rd` WSLs are installed

Also note that during the build we always get the message `Script is already elevated, no need to restart.` because the `Restart-ScriptForElevation` function is called twice. On the first time it quietly escalates itself to admin without a message. Then when it's called the second time, we get the message.  I think it might be clearer to users to not bother giving that message at all.

2021-09-21 21:17 UTC, mattfarina commented
@ericpromislow Did you try the pre-built version from the CI system?

2021-09-23 17:01 UTC, ericpromislow approved these changes

2021-09-23 17:18 UTC, merged