Do not update /etc/hosts when integration is enabled
rancher-sandbox/rancher-desktop pull request #6431
Opened 2024-02-06 20:17 UTC by Nino-K

Related to: https://github.com/rancher-sandbox/rancher-desktop/issues/6245

2024-02-06 22:11 UTC, mook-as reviewed
This code is for the foreign distros (e.g. `ubuntu`); is removing that intended?

2024-02-07 16:21 UTC, Nino-K commented
> This code is for the foreign distros (e.g. `ubuntu`); is removing that intended?

Yes, we no longer need to touch their `/etc/hosts` file.

2024-02-07 18:10 UTC, mook-as requested changes
Nino says to not merge.

(Please edit the description instead of putting it in a random comment; that's too easy to miss)

2024-02-21 18:03 UTC, mook-as approved these changes
The change looks fine. I assume we'd expose ports on the default network namespace as needed? Because currently there would be no way for other distros to connect to services exported by containers, I think?

2024-02-26 20:31 UTC, merged