Ensure the rd node has the builder label on it
rancher-sandbox/rancher-desktop pull request #677
Opened 2021-09-25 00:29 UTC by ericpromislow

Kim expects its builder daemonset to use the node selector
node-role.kubernetes.io/builder=true

Sometimes on restart this label is dropped off the
lima-rancher-desktop node, so we can ensure it's always there.

Signed-off-by: Eric Promislow <epromislow@suse.com>

2021-09-25 00:57 UTC, mook-as requested changes

2021-09-25 00:57 UTC, mook-as commented on src/k8s-engine/lima.ts
> +        ['label', '--overwrite', 'nodes', 'lima-rancher-desktop', 'node-role.kubernetes.io/builder=true'],
We can't hard-code `lima-rancher-desktop` here.

2021-09-25 01:02 UTC, mook-as commented on src/k8s-engine/lima.ts
> +        ['label', '--overwrite', 'nodes', 'lima-rancher-desktop', 'node-role.kubernetes.io/builder=true'],
```suggestion
        ['label', '--overwrite', 'nodes', '--all', 'node-role.kubernetes.io/builder=true'],
```

2021-09-25 06:00 UTC, jandubois commented
Running the latest version throws an error for me:

```console
$ cat background.log
Expected error moving Lima state: Error: ENOENT: no such file or directory, rename '/Users/jan/Library/State/rancher-desktop/lima' -> '/Users/jan/Library/Application Support/rancher-desktop/lima'
Kubernetes was unable to start: Error: /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 1
    at ChildProcess.<anonymous> (/Applications/Rancher Desktop.app/Contents/Resources/app.asar/dist/app/background.js:1:7514)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Running the label command manually works fine:

```console
$ "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/kubectl" label --context rancher-desktop --overwrite nodes lima-rancher-desktop "node-role.kubernetes.io/builder=true"
node/lima-rancher-desktop labeled
```

2021-09-26 22:36 UTC, jandubois commented
I've hidden my previous comment, as it seems to describe an error that only happens when you upgrade from a previous (non-working) test build.

However, this build does not work for me; it does not set the node-role label during the restart.

But even more interesting, when I was redoing all the test starting with a fresh install of 0.4.1: It never drops any of the node labels during a restart:

```
$ k get no -o json | jq '.items[0].metadata.labels' | grep node-role
kubectl get no -o json
  "node-role.kubernetes.io/builder": "true",
  "node-role.kubernetes.io/control-plane": "true",
  "node-role.kubernetes.io/master": "true",
```

As soon as I upgraded to `0.4.1-293-g526ae16`, all **three** node-role labels were gone. So even if restoring the `builder` role worked, there is still the question about what we need to do about the `master` and `control-plane` roles?

I think we need to go back to understanding why the roles are lost on the restart, and not just try to fix it up afterwards. Maybe there is something else missing that we haven't discovered yet.

2021-09-26 22:52 UTC, jandubois commented
Also when I run this build after deleting any previous RD install, I get the generic "kubectl failed" error:

```
There was an unknown error starting Kubernetes: Error: /Applications/Rancher
Desktop.app/Contents/Resources/resources/darwin/bin/kubectl exited with code 1
```

after runnining

```console
$ cd ~/cd Library
$ rm -rf Logs/rancher-desktop Preferences/rancher-desktop "Application Support/rancher-desktop"
```

2021-09-26 23:04 UTC, jandubois commented
Further testing shows that I can manually stop and restart the RD lima node without dropping the labels:

```console
$ k get no -o json | jq '.items[0].metadata.labels' | grep node-role
  "node-role.kubernetes.io/control-plane": "true",
  "node-role.kubernetes.io/master": "true",

$ LIMA_HOME="/Users/jan/Library/Application Support/rancher-desktop/lima" limactl stop 0
[...]
INFO[0007] [hostagent] QEMU has exited

$ LIMA_HOME="/Users/jan/Library/Application Support/rancher-desktop/lima" limactl start 0
[...]
INFO[0019] READY. Run `limactl shell 0` to open the shell.

$ LIMA_HOME="/Users/jan/Library/Application Support/rancher-desktop/lima" limactl shell 0 sudo rc-service k3s start
 * Starting k3s ...
 
$ k get no -o json | jq '.items[0].metadata.labels' | grep node-role
  "node-role.kubernetes.io/control-plane": "true",
  "node-role.kubernetes.io/master": "true",
```

This was again with a fresh setup, so there is no `builder` role at all.

2021-09-26 23:10 UTC, jandubois commented
Starting once more with a fresh install, I've stopped RD, and then restarted the VM manually as in the comment above. The labels were still there. So it must be some activity by RD that is dropping the labels as a side effect.

2021-09-26 23:12 UTC, jandubois commented
@mook-as I'm giving up now; can you continue to look into this? If we can fix the reason why we are dropping the labels, then we don't need this PR at all.

2021-09-27 18:16 UTC, ericpromislow commented
And another obsolete PR -- the problem is that we were  asynchronously deleting the `lima-rancher-desktop` node -- fix is to stop deleting it

2021-09-27 18:16 UTC, closed without merging