Completely remove vde_vmnet; socket_vmnet is the only supported option
rancher-sandbox/rancher-desktop pull request #6975
Opened 2024-06-01 00:23 UTC by jandubois

2024-06-03 17:08 UTC, jandubois commented
I ran a full BATS cycle with QEMU and containerd on macOS with the CI build, and it passed all 504 tests. I'm not running any other combinations right now, so don't wait for that 😄.

2024-06-04 20:46 UTC, mook-as requested changes

2024-06-04 20:46 UTC, mook-as commented on e2e/backend.e2e.spec.ts
> -        darwin: { experimental: { virtualMachine: { socketVMNet: getAlternateSetting(currentSettings, 'experimental.virtualMachine.socketVMNet', true, false) } } },
This was here to test platform-specific settings; can we switch to a different platform-specific one instead, such as `useRosetta`?

2024-06-04 20:46 UTC, mook-as commented on e2e/backend.e2e.spec.ts
> +      const platformExpectedDefinitions: Partial<Record<NodeJS.Platform, ExpectedDefinition>> = { win32: { 'virtualMachine.hostResolver': false } };
See above — we should still have a platform-specific thing (to test that things switch off correctly on Windows).

2024-06-04 20:46 UTC, mook-as commented on pkg/rancher-desktop/config/__tests__/settings.spec.ts
> -          experimental: {
It doesn't make much sense to delete this: people with old config files would still have it, we need to test that we migrate it correctly (by dropping the field).

2024-06-04 20:46 UTC, mook-as commented on pkg/rancher-desktop/config/settingsImpl.ts
> -      { oldPath: 'kubernetes.experimental.socketVMNet', newPath: 'experimental.virtualMachine.socketVMNet' },
This should stay (or be changed to a `_.unset()`).

2024-06-04 20:46 UTC, mook-as commented on pkg/rancher-desktop/config/settingsImpl.ts
> -      { oldPath: 'virtualMachine.experimental.socketVMNet', newPath: 'experimental.virtualMachine.socketVMNet' },
Same as above.

2024-06-04 20:46 UTC, mook-as commented on pkg/rancher-desktop/config/settingsImpl.ts
There should be a new migration to delete the pref we're dropping.

2024-06-04 20:46 UTC, mook-as commented on pkg/rancher-desktop/config/settings.ts
> -      socketVMNet: false,
Should that lead to a settings version bump?

2024-06-05 21:57 UTC, mook-as approved these changes

2024-06-05 22:00 UTC, merged