Vendor sudo-prompt module into our repo
rancher-sandbox/rancher-desktop pull request #7398
Opened 2024-08-30 19:23 UTC by jandubois

The upstream repo has been archived in 2021 and no longer accepts PRs.

This vendoring is in preparation to update the bundled AppleScript applet to include aarch64 support (#7336), so it no longer requires Rosetta on M1+ machines.

2024-08-30 23:22 UTC, jandubois commented
Sorry for asking prematurely to review this PR, but I think it is now ready.

`test.js` has been disabled by renaming it to `test-orig.js`. The test wasn't performed before because `yarn install` doesn't run it, and I don't see how it could work in CI given that it displays a prompt and waits for user input.

2024-08-30 23:23 UTC, mook-as requested changes
Happy to see that linter fixes were in separate commits, so we have a view of what the upstream code looked like.

It would have been nice to import the upstream repo with commits (like we did for the `src/go/` merge), instead of as a snapshot, but I'm not sure you feel like doing the work…

(Requesting just the jest ignore bit; everything is acceptable.)

2024-08-30 23:23 UTC, mook-as commented on pkg/rancher-desktop/sudo-prompt/test-orig.js
I think it would be better to leave the name as-is and to edit our [jest configuration file](https://github.com/rancher-sandbox/rancher-desktop/blob/016c9e7c30fed9225da75a3e858274f18de75770/jest.config.js) to add this to the [`testPathIgnorePatterns`](https://jestjs.io/docs/configuration#testpathignorepatterns-arraystring).  Sorry, didn't think to look until I started doing the review…

I don't see how the test might be run non-interactively without weird setup, so I guess it's reasonable that we don't have a follow-up to fix this…

2024-08-30 23:23 UTC, mook-as commented on pkg/rancher-desktop/sudo-prompt/test-concurrent.js
I guess this test isn't running either? It doesn't look any closer to passing that the other file…

2024-08-30 23:29 UTC, jandubois commented on pkg/rancher-desktop/sudo-prompt/test-concurrent.js
It is not being run. It seems like when the `package.json` doesn't include a `scripts` object with a `test` script, then it will execute `test.js` via node. That's why renaming `test.js` worked to disable it.

2024-08-30 23:36 UTC, jandubois commented on pkg/rancher-desktop/sudo-prompt/test-orig.js
Add `testPathIgnorePatterns`; let's see if it works...

2024-08-31 00:21 UTC, mook-as approved these changes

2024-08-31 00:21 UTC, merged