Bind WSL-Proxy Process to Specified IP Address
rancher-sandbox/rancher-desktop pull request #7552
Opened 2024-09-26 18:21 UTC by Nino-K

This changes the binding of the WSL-Proxy process from always using localhost to utilizing the specified host IP address for port bindings.

Previously, binding exclusively to localhost caused issues for users who needed to define port bindings that extended beyond this address. The new approach ensures that the proxy listens on the provided hostIP.

Fixes: https://github.com/rancher-sandbox/rancher-desktop/issues/7550

2024-09-26 18:53 UTC, mook-as requested changes
Tracking down where `portBinding.HostIP` comes from…

The whole `pm` comes from:
https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/tracker/apitracker.go#L119
We copy the mapping from:
https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/tracker/apitracker.go#L88-L91

As an example, for containerd it's just straight out of the event JSON:
https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/containerd/events.go#L398

This means that `portBinding.HostIP` is from the point of view of the RD network namespace.  Therefore using that `HostIP` directly is not the correct thing to do, since it can be `192.168.143.1` (that is, eth0 for the namespace), which is invalid in the default namespace (where wsl-port-proxy runs).

I think we should instead check if `portBinding.HostIP` is `localhost`, and use `0.0.0.0` if it's not.

If my thinking is incorrect here, please let me know.

2024-09-27 16:44 UTC, Nino-K commented
> Tracking down where `portBinding.HostIP` comes from…
> 
> The whole `pm` comes from:
> 
> https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/tracker/apitracker.go#L119
> 
> 
> We copy the mapping from:
> https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/tracker/apitracker.go#L88-L91
> 
> As an example, for containerd it's just straight out of the event JSON:
> 
> https://github.com/rancher-sandbox/rancher-desktop/blob/3cf2b5d9c5f1ca5fd4ad7aa0d365e8f3e9e56c51/src/go/guestagent/pkg/containerd/events.go#L398
> 
> This means that `portBinding.HostIP` is from the point of view of the RD network namespace. Therefore using that `HostIP` directly is not the correct thing to do, since it can be `192.168.143.1` (that is, eth0 for the namespace), which is invalid in the default namespace (where wsl-port-proxy runs).
> 
> I think we should instead check if `portBinding.HostIP` is `localhost`, and use `0.0.0.0` if it's not.
> 
> If my thinking is incorrect here, please let me know.

The only valid options for the IP address from user input are localhost or 0.0.0.0. For example, valid formats for the -p argument include -p 127.0.0.1:6601:80 or -p 6601:80. Therefore, the HostIP must always be either localhost or 0.0.0.0. Providing any other addresses in the -p argument that are not accessible to the Docker proxy will result in an error, such as:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint xenodochial_liskov (044b082e31952f657903daee6acf97d266c6e867720f81c9672a4e948ff95a5c): Error starting userland proxy: listen tcp4 172.27.176.1:6604: bind: cannot assign requested address.
``` 
However, there is a caveat. If a user knows the internal namespace IP and specifies an internal IP address that is available to the Docker proxy, like this:

```
docker run -d -p 192.168.127.2:6604:80 nginx
```
This will succeed, and the Docker proxy will bind to that IP address. However, the user will not be able to access their port. This situation is a bug in our system. It should not be addressed in the WSL proxy but rather fixed at the source in the guest agent where the port mappings are processed. As discussed previously, this should be addressed in a separate PR for the guest agent. Overall, using the HostIP in this context is the correct approach.

2024-09-27 16:55 UTC, mook-as commented
Right, I'm specifically thinking about the case of using the `eth0` in the network namespace (i.e. `192.168.127.2` or whatever in that subnet).  The fact that the user can't access that port _is_ the bug we're trying to fix here…

> As discussed previously, this should be addressed in a separate PR for the guest agent.

I don't recall that; could you refresh my memory?

> Overall, using the HostIP in this context is the correct approach.

… But that's why I was tracking down where `HostIP` came from to figure out that it makes no sense in context?

2024-09-27 17:28 UTC, mook-as approved these changes
Okay, we'll define `HostIP` to mean the VM host (i.e. Windows); this does mean that the PR is still wrong when it refers to, e.g. _Local Network Connection 1_ (i.e. the Windows equivalent of `eth0`), but it's better than before.

2024-09-27 17:58 UTC, Nino-K commented
> this does mean that the PR is still wrong when it refers to, e.g. _Local Network Connection 1_ (i.e. the Windows equivalent of `eth0`), but it's better than before.

I'm not too sure if that statement is correct at all, the PR is still doing the right thing by using the HostIP given that we only have two options either `localhost` or `0.0.0.0`, and this has always been a know thing in our system.

2024-09-27 23:32 UTC, merged