Set correct host arch in lima.yaml
rancher-sandbox/rancher-desktop pull request #933
Opened 2021-11-09 23:00 UTC by jandubois

2021-11-16 12:39 UTC, DevPre24 commented
@jandubois Hi, thanks for your efforts porting it to the m1.

I was doing a little bit of testing, but unfortunately on my system (MBP 13 M1) the limavm virtual machine doesn't seem to start, i get this error:

```[Bds]Booting UEFI Misc Device
 BlockSize : 262144 
 LastBlock : FF 
[Bds] Expand VenHw(93E34C7E-B50E-11DF-9223-2443DFD72085,00) -> <null string>
BdsDxe: failed to load Boot0001 "UEFI Misc Device" from VenHw(93E34C7E-B50E-11DF-9223-2443DFD72085,00): Not Found
Memory  Previous  Current    Next   
 Type    Pages     Pages     Pages  
======  ========  ========  ========
  09    00000000  00000090  000000B4
  0A    00000000  00000030  0000003C
  00    00000000  00000300  000003C0
  06    0000012C  00000330  000003FC
  05    00000096  00000250  000002E4
  03    000003E8  00000483  000005A3
  04    00002EE0  0000217D  00002EE0
  01    00000014  00000000  00000014
  02    00000000  00000000  00000000
Memory Type Information settings change.
[Bds]Booting UEFI Misc Device 2
 BlockSize : 512 
 LastBlock : 53FFF 
PartitionDxe: El Torito standard found on handle 0x13E2D6E98.
 BlockSize : 512 
 LastBlock : F 
 BlockSize : 512 
 LastBlock : 2CFF 
FatDiskIo: Cache Page OutBound occurred! 
 BlockSize : 512 
 LastBlock : 53FFF 
PartitionDxe: El Torito standard found on handle 0x13E2D6E98.
 BlockSize : 512 
 LastBlock : F 
 BlockSize : 512 
 LastBlock : 2CFF 
[Bds] Expand PciRoot(0x0)/Pci(0x4,0x0) -> <null string>
BdsDxe: failed to load Boot0002 "UEFI Misc Device 2" from PciRoot(0x0)/Pci(0x4,0x0): Not Found
Memory  Previous  Current    Next   
 Type    Pages     Pages     Pages  
======  ========  ========  ========
  09    00000000  00000090  000000B4
  0A    00000000  00000030  0000003C
  00    00000000  00000300  000003C0
  06    0000012C  00000330  000003FC
  05    00000096  00000250  000002E4
  03    000003E8  00000483  000005A3
  04    00002EE0  0000217D  00002EE0
  01    00000014  00000000  00000014
  02    00000000  00000000  00000000
Memory Type Information settings change.```

Workflow:
- Cloned the project
- Checked out the `m1 branch`
- Built using nodejs 14 (both amd64 and arm64, btw the electron component seems to run natively as well, no clue if it has some issues so i tried both)
- Replaced `alpine-lima-rd` and `lima-and-qemu` in the Applications files with those provided

2021-11-16 18:52 UTC, bdhoine commented
I managed to take this branch as a base to run Rancher Desktop as a native app on my m1. I did patch some stuff where the electron helper methods are used and some other patches to have the binaries be auto downloaded by the install scripts. The vm starts and I was able to run an nginx pod and expose it on port 8080.

2021-11-16 21:38 UTC, mook-as requested changes

2021-11-16 21:38 UTC, mook-as commented on src/k8s-engine/lima.ts
> +      const k3s = Electron.app.runningUnderRosettaTranslation ? 'k3s-arm64' : 'k3s';
This should depend on the `arch` we passed in the constructor instead.

2021-11-16 21:38 UTC, mook-as commented on src/k8s-engine/lima.ts
> +        arch:     Electron.app.runningUnderRosettaTranslation ? 'aarch64' : 'x86_64',
This should depend on the `arch` we passed in the constructor instead.

2021-11-16 21:43 UTC, jandubois commented on src/assets/scripts/install-k3s
> +if [ "$(uname -m)" = "aarch64" ]; then
We'll have to change things. Just like we'll have to change the code again once we build a native GUI.

2021-11-18 18:29 UTC, mook-as requested changes

2021-11-18 18:29 UTC, mook-as commented on src/k8s-engine/lima.ts
> +import Electron from 'electron';
Is this import still used?

2021-11-18 18:48 UTC, jandubois commented
Converted to "draft" mode because I will add packaging changes here as well.

2021-11-18 23:46 UTC, jandubois commented on src/k8s-engine/lima.ts
> +import Electron from 'electron';
No (removed)

2021-11-19 22:18 UTC, mook-as submitted a review, later dismissed
Tried the build from CI, and it worked (after manually skipping the prompt due to unverified developer).

It doesn't have correct permissions to handle the integrations (`/usr/local/bin` stuff).  But that can be dealt with later.

2021-11-19 22:21 UTC, jandubois commented on .github/workflows/package.yaml
> +            mv dist/Rancher*.zip "dist/$(basename dist/Rancher*.zip .zip)-x86_64.zip"
> if we're going to ignore the file name when we do the upload

Not sure what you mean: we do upload with a wildcard, but this is still the filename that will be used in the assets list (and in the checksums file).

2021-11-19 22:22 UTC, jandubois commented on .github/workflows/package.yaml
> +            mv dist/Rancher*.zip "dist/$(basename dist/Rancher*.zip .zip)-x86_64.zip"
Without this change the filenames are identical for both builds.

2021-11-19 22:29 UTC, jandubois commented on .github/workflows/package.yaml
> +            mv dist/Rancher*.zip "dist/$(basename dist/Rancher*.zip .zip)-x86_64.zip"
No, we don't need the renames; they do nothing for us. I've removed them.

2021-11-19 22:42 UTC, jandubois commented
> It doesn't have correct permissions to handle the integrations (/usr/local/bin stuff). But that can be dealt with later.

I think you will observe the same issues when you install on a fresh install on Intel as well (pristine Big Sur VM):

```console
% sw_vers 
ProductName:	macOS
ProductVersion:	11.3
BuildVersion:	20E232
% ls -la /usr/local
total 0
drwxr-xr-x   2 root  wheel   64  1 Jan  2020 .
drwxr-xr-x@ 11 root  wheel  352  1 Jan  2020 ..
```

2021-11-19 23:32 UTC, jandubois commented
>the limavm virtual machine doesn't seem to start, i get this error (serial console)

@DevPre24 It didn't work because you were building natively on M1, but the code was only checking if it was running under Rosetta. I've updated the code today to also check `os.arch()`, so maybe it works better now.

However, I did try to cross-build a native app on Intel, and that didn't work. I gave up on it because we also are using a few node modules that are platform-dependent, so those wouldn't work unless compiled on ARM.

For now we will ship the GUI running via Rosetta because we have no way to run Github Actions on M1 machines, so couldn't produce builds using CI.

2021-11-23 02:01 UTC, mook-as approved these changes
Looks reasonable to me; we can do follow-ups as needed.

2021-11-23 03:48 UTC, merged