[Improvement] ipcRenderer.SendSync to ipcRenderer.invoke
rancher-sandbox/rancher-desktop pull request #949
Opened 2021-11-12 21:52 UTC by evertonlperes

### Changes
1. Replaced remaining `ipcRenderer.SendSync('settings-read')` in vue files to `ipcRenderer.invoke('settings-read')`

Motivator:
https://github.com/rancher-sandbox/rancher-desktop/pull/855
Our E2E tests was really intermittent and it was crashing during the `SendSync` event. As our E2E perform on an `async` way, replacing it to `.invoke` have mitigated the flaky/intermittence caused by `SendSync` method.
Here's a reference to replace `SendSync` to `invoke`: 
![Screen Shot 2021-11-12 at 3 48 55 PM](https://user-images.githubusercontent.com/37411123/141538564-0c3c45c5-4d39-4436-9f34-a9dd45449e9c.png)
Ref: [ipcRenderer.SendSync()](https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrenderersendsyncchannel-args)

2021-11-18 20:04 UTC, mook-as approved these changes

2021-11-19 19:34 UTC, evertonlperes commented
Just fixed a merge conflict on the last push.
Could you guys take a look again? @mook-as @ericpromislow ?

Thanks!

2021-11-19 20:19 UTC, ericpromislow requested changes

2021-11-19 20:19 UTC, ericpromislow commented on src/pages/K8s.vue
> +    (async() => {
I think we should minimize our uses of `ipcRenderer.invoke` in the UI, and instead break it into a `send` and an `on`, like the use of `images-namespaces` and `images-namespaces-read` at https://github.com/rancher-sandbox/rancher-desktop/blob/f3d631a161ac684983b81329781ce5c44ddc9acf/src/pages/Images.vue#L95  (but please wait for Mark's opinion).

2021-11-19 20:19 UTC, ericpromislow commented on src/pages/PortForwarding.vue
> +    (async() => {
Same comment as above.

2021-11-19 20:19 UTC, ericpromislow commented on src/pages/K8s.vue
> +      settings:             defaultSettings,
Initing to `defaultSettings` is good.

2021-11-25 19:37 UTC, ericpromislow commented
Merge conflicts in FirstRun.vue -- please rebase and push

2021-11-25 22:09 UTC, ericpromislow approved these changes
LGTM

2021-11-25 22:53 UTC, merged